### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by fredatgithub** [unvell/ReoGrid#1]
Hello Jing,
Thanks for putting your project on GitHub.
If you need help on translation into French, I can help.

**Comment by jingwood** [comment]
Hi fred! 
OK Thanks a lot! Where to put the translated document?

**Comment by fredatgithub** [comment]
Hi,
Post it to the releases tab.

**Comment by fredatgithub** [comment]
Hello Jing,
you can send your file to my gmail box.

**Comment by alexey77777** [comment]
Hello (Bonjour), Jing and Fred

Jing, do you plan to continue to update the page "Change Log"? (https://reogrid.net/change-log/)
Information for the Russian version of the documentation, I usually took on this page (change log).
Documentation in the Ukrainian language: I'm not yet sure whether - whether it is necessary.

**Comment by fredatgithub** [comment]
hello,
I have created a GitHub project 
https://github.com/fredatgithub/TranslationReoGridWebSite
We can start with this.

**Comment by alexey77777** [comment]
Hello
Fred, you have a very good idea, but it's no support for some features of the existing documentation projects.
The original document format - a few pages in English. Examples of only the language C#.
Russian version - is one HTML-file with examples for languages VB, C#.

In the Russian version of the documentation is one feature - it is a separate project, which consists of 2 solutions Visual Studio 2012 (All code snippets in VB and C# + "builder").
When I came to "ReoGrid" project, Jing asked me to do my version of the project documentation.
Therefore, HTML-file Russian documentation assembled from HTML-template and code snippets on VB, C#. This is a mini-book with pictures and videos: https://reogrid.net/ru/document/v1-3-0/

Will you be able to consider these features in your project?
(If I understand correctly, then someone has to break the English version of the site into fragments, and the other participants must re-create this structure in its language versions).

**Comment by jingwood** [comment]
Thanks Fred and Alexey!

I have created a website https://reogrid.net/fr for French language documents. The website server keeps all documents in database and backup automatically every day.

**Comment by alexey77777** [comment]
Thanks, Jing)

We need to wait for a response from Fred: he clearly knows French better than I)

**Comment by fredatgithub** [comment]
hello,
I have created a GitHub project 
https://github.com/fredatgithub/TranslationReoGridWebSite
We can start with this.

**Comment by alexey77777** [comment]
Fred,
Any ideas on how to convert this: https://reogrid.net/ru/document/v1-3-0/ and this: https://reogrid.net/document  into your proposed template:

<?xml version="1.0" encoding="utf-8" ?>
<terms>
</terms>

???

**Comment by alexey77777** [comment]
Changes in the Russian documentation: deleted marks "Pro-edition", added information about paid services.

**Comment by fredatgithub** [comment]
Hello,
@alexey77777, no need to use my created gitHub project 
[https://github.com/fredatgithub/TranslationReoGridWebSite](https://github.com/fredatgithub/TranslationReoGridWebSite)
because Jing created a French web site
 [https://reogrid.net/fr](https://reogrid.net/fr)
so the solution for new languages is to ask Jing to create a new web site from English and then the translator will access it and translate it.

**Comment by alexey77777** [comment]
Hello, Fred)

Thank you for this information :-)
2 days ago I saw your translated pages on this site (reogrid.net/fr) - it's great :-)

> so the solution for new languages is to ask Jing to create a new web site from English and then the translator will access it and translate it.

Thanks) So we made a Russian version of the site: reogrid.net/ru

The more sites, the more time it takes to update them when new releases of the engine sites. So about whether it makes sense to do a separate site for the Ukrainian language, we need to think twice .. It may be enough support in this language.

**Comment by fredatgithub** [comment]
Hello Alexey,
It is up to Jing to decide how the translation of ReoGrid.net web site should be done.
One XML file for all the terms in one application should be the best solution but it may be difficult to adapt if Jing has already started with a different approach.
