### ISSUE TITLE
None of the Built-in cell types working in VB.net

### ISSUE THREAD

**Issue by fliptoback** [unvell/ReoGrid#105]
Hi, I am trying to build a listbox to a cell and tried to follow this guide here:
https://reogrid.net/document/dropdown-cell/

The problem is when I define the list 
`Dim dropdown As New DropdownListCell("Apple", "Orange", "Banana", "Pear", "Pumpkin", "Cherry", "Coconut"), `
VB.net says Type 'Dropdownlistcell' is not defined.

Not sure what I am doing wrong so I tried out the other built-in cell types, but even the most basic buttoncell is also not working.

`.CurrentWorksheet("B3") = New Buttoncell("Hello")`

also return the error as Type Buttoncell is not defined.

Could someone please enlighten me what I am doing wrong?

Thanks

**Comment by jingwood** [comment]
Make sure you have imported the namespace `unvell.ReoGrid.CellTypes` and using the correct class name. (case sensitive)

- DropDownListCell
- ButtonCell

**Comment by fliptoback** [comment]
Thanks jing. You are a legend. It works!!
