### ISSUE TITLE
Binaries are not signed

### ISSUE THREAD

**Issue by Dunkhan** [unvell/ReoGrid#106]
The reogrid binaries are not signed using the strong-name system https://docs.microsoft.com/en-us/dotnet/framework/app-domains/create-and-use-strong-named-assemblies

This has the side effect that it is not possible to create a signed assembly that has reogrid as a dependency.

**Comment by jingwood** [comment]
Now the DLLs will be published as strong-named assemblies since v3.0.0.
Thanks for your suggestion!
