### ISSUE TITLE
When scrolling the colors are turning white [WPF]

### ISSUE THREAD

**Issue by Sesi0** [unvell/ReoGrid#107]
So I have this:
![image](https://user-images.githubusercontent.com/10748411/37777162-94d4f2f6-2def-11e8-9c5d-24d272984fb8.png)

And when I scroll my rectangles goes like this:
![image](https://user-images.githubusercontent.com/10748411/37777321-eae8276c-2def-11e8-8609-563087239264.png)

Even with the frozen areas disabled it's the same..

**Comment by Sesi0** [comment]
Ok, this is because I try to set data on invalid cell, and in my custom body I have a tooltip and popup which uses custom object for datacontext for the popup and for the tooltip's content just the data of the cell nvm that is is invalid, idk why but works and breaks the color. When I used cell.Tag for the invalid cells tooltip again worked but the colors were not damaged like in the picture. Hope this helps you to fix for future patches.

**Comment by jingwood** [comment]
Thanks @Sesi0! Will close this issue.
