### ISSUE TITLE
The function OR return empty when arguments are all False

### ISSUE THREAD

**Issue by enoksaju** [unvell/ReoGrid#108]
i try the function OR on a cell.

=OR(FALSE, FALSE)

but, this return me  empty instead of FALSE,

if i combine the function OR with the function IF and the result of OR are FALSE, this return me an Empty Value, EXAMPLE:

=IF(OR(FALSE,FALSE), "OK", "BAD") //RETURN empty instead of "BAD"

**Comment by enoksaju** [comment]
i search the function OR on master Code:

                #region OR
		public static FormulaValue Or(Cell cell, List<STNode> list)
		{
			foreach (var node in list)
			{
				FormulaValue val = Evaluator.Evaluate(cell, node);

				if (val.type == FormulaValueType.Boolean)
				{
					if ((bool)val.value == true)
					{
						return= true;
					}
				}
				else if (val.type == FormulaValueType.Number)
				{
					return =((double)val.value != 0);
				}
			}
			throw new FormulaTypeMismatchException(cell);
		}
		#endregion // OR

and change to this:


                #region OR
		public static FormulaValue Or(Cell cell, List<STNode> list)
		{
			var ret = false;

			foreach (var node in list)
			{
				FormulaValue val = Evaluator.Evaluate(cell, node);

				if (val.type == FormulaValueType.Boolean)
				{
					if ((bool)val.value == true)
					{
						ret= true;
					}
				}
				else if (val.type == FormulaValueType.Number)
				{
					ret =((double)val.value != 0);
				}
			}

			return ret;

			throw new FormulaTypeMismatchException(cell);
		}
		#endregion // OR

**Comment by jingwood** [comment]
You can consider to submit a pull request and we will apply you changes.

**Comment by jingwood** [comment]
@enoksaju Thanks! This problem has been fixed by #295.
