### ISSUE TITLE
ReoGrid WPF Script Execution

### ISSUE THREAD

**Issue by AbhijeetChowdhury** [unvell/ReoGrid#113]
Hi,

I need to run an existing Reoscript file after the grid is loaded.

I am using WPF as frontend and have a reference to unvell.ReoGrid.dll and unvell.ReoGridWpf.dll.

Thanks in advance.

**Comment by jingwood** [comment]
What is your question? You need use the extension feature-supported DLL which can be download from https://reogrid.net/download

**Comment by AbhijeetChowdhury** [comment]
Hi @jingwood ,

Thanks for the quick reply.
