### ISSUE TITLE
Scroll Event?

### ISSUE THREAD

**Issue by patchcad** [unvell/ReoGrid#114]
Hi Jing,

Is it possible to get an event when a use moves the horizontal and/or vertical scroll bars? I'm trying to synchronize two instances to ReoGrid but cannot find any appropriate event or access to the internal scrollbar controls.

Thank you!

Adam

**Comment by jingwood** [comment]
@patchcad Please see the demo program in the release package that can be downloaded from https://reogrid.net/download, there is an example program that implements the synchronized scroll between two instances of grid.

**Comment by patchcad** [comment]
Absolutely spot on! Thank you so much!!!
