### ISSUE TITLE
How to add ImageObject to the specified celladd image throught cellPosition

### ISSUE THREAD

**Issue by KellyGodLv** [unvell/ReoGrid#117]
eg: I want to add image to A1:G10

**Comment by jingwood** [comment]
Like Excel, `FloatingImage` cannot be putted into a cell, instead you can use `ImageCell` that is an extension cell type that can hold an image inside. For details see https://reogrid.net/document/built-in-cell-types/

**Comment by KellyGodLv** [comment]
tnks your answer! but ImageCell don't save to rgf or excel2007 ,
