### ISSUE TITLE
When I was exported to HTML, the exported HTML diagram could not be displayed correctly.

### ISSUE THREAD

**Issue by dhsg521** [unvell/ReoGrid#120]
```
 string path = System.Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData) + "\\share.html";
                using (FileStream fs = new FileStream(path, FileMode.Create, FileAccess.Write))
                {
                    worksheet.ExportAsHTML(fs, "data");
                }
```

**Comment by jingwood** [comment]
Please describe your problem in more detail, what kind of `incorrect` during the html displaying.

**Comment by dhsg521** [comment]
@jingwood I use ReoGrid to export Html,but the diagram which in the sheet could not be displayed correctly.

**Comment by dhsg521** [comment]
@jingwood For example, I have a linechat in my sheet, but I export sheet as Html，the linechat is not in Html.

**Comment by jingwood** [comment]
Charts currently are not implemented to be exported as HTML.

**Comment by dhsg521** [comment]
@jingwood  Ok！Thanks！I implemented it with Html parser.
