### ISSUE TITLE
Error when loading xlsx with line chart.

### ISSUE THREAD

**Issue by NPR18041** [unvell/ReoGrid#127]
An error occured while trying to load an xlsx file containing line chart inside.
but when I deleted line chart from xlsx file and load file again, It worked.

Error this line `workBook.Load(pathFileTextBox.Text, FileFormat.Excel2007, Encoding.UTF8);`.

> ...
> A first chance exception of type 'unvell.ReoGrid.Formula.FormulaParseException' occurred in unvell.ReoGrid.dll
> unvell.ReoGrid.Formula.FormulaParseException: unexpect token:  point
>    at unvell.ReoGrid.Formula.Parser.Parse(IWorkbook workbook, Cell cell, String input)
>    at unvell.ReoGrid.Formula.Evaluator.Evaluate(IWorkbook workbook, String input)
>    at unvell.ReoGrid.IO.OpenXML.ExcelReader.ReadDataSerial(WorksheetChartDataSource dataSource, Worksheet rgSheet, IChartSerial serial)
>    at unvell.ReoGrid.IO.OpenXML.ExcelReader.LoadChart(Worksheet rgSheet, ChartSpace chartSpace)
>    at unvell.ReoGrid.IO.OpenXML.ExcelReader.LoadGraphic(Document doc, Worksheet rgSheet, Drawing drawingFile, GraphicFrame graphicFrame)
>    at unvell.ReoGrid.IO.OpenXML.ExcelReader.LoadDrawingObjects(Document doc, Worksheet sheet, Worksheet rgSheet, Drawing drawingFile)
>    at unvell.ReoGrid.IO.OpenXML.ExcelReader.LoadWorksheet(IWorkbook rgWorkbook, Document doc, WorkbookSheet sheetIndex)
>    at unvell.ReoGrid.IO.OpenXML.ExcelReader.ReadStream(IWorkbook rgWorkbook, Stream stream)
>    at unvell.ReoGrid.IO.ExcelFileFormatProvider.Load(IWorkbook workbook, Stream stream, Encoding encoding, Object arg)
>    at unvell.ReoGrid.Workbook.Load(Stream stream, FileFormat fileFormat, Encoding encoding)
>    at unvell.ReoGrid.Workbook.Load(String path, FileFormat fileFormat, Encoding encoding)
>    at unvell.ReoGrid.ReoGridControl.Load(String path, FileFormat fileFormat, Encoding encoding)
> ...
> 

How to fix it. Check it please.
@jingwood 
Thank you.

**Comment by jingwood** [comment]
It looks like something syntax used in formula from Excel that ReoGrid doesn't support. `point`? You may ignore this problem if you don't care the formula.

**Comment by NPR18041** [comment]
I found it.
Thank you.
