### ISSUE TITLE
Vertical scroll width

### ISSUE THREAD

**Issue by shlomobr** [unvell/ReoGrid#128]
I am trying to determine the width of my cells in respect to the control width, so that I don't have a problem running my app in different computers, but the scroll width has been an issue for this. Does anyone know how to determine exactly the vertical scroll width for a ReoGrid?

**Comment by jingwood** [comment]
Do you use the WPF edition?

**Comment by jingwood** [comment]
Can you provide an image or test project to describe the problem?

**Comment by jingwood** [comment]
I'm going to close this and if you still have this problem please open the new.
