### ISSUE TITLE
Show or Hide sheets without deleting them

### ISSUE THREAD

**Issue by Furgia** [unvell/ReoGrid#134]
After creating a reogrid object with n sheet is there a way to dynamically remove some sheets from the visualization without deleting them so that they can then be redisplayed with the reverse command  ?
Thank you

**Comment by jingwood** [comment]
Use `reogrid.RemoveWorksheet` to remove worksheet dynamically. `remove` is not `delete`, if you have the instance of worksheet, you can add it back into workbook using `reogrid.AddWorkbook` method.

```csharp
// find instance of worksheet
var mysheet = reogrid.Worksheets["name"];

// remove it from workbook temporarily 
reogrid.RemoveWorksheet(mysheet);

...

// add it back into workbook
reogrid.AddWorksheet(mysheet);
```
