### ISSUE TITLE
Scroll behaviour is incorrect in wpf

### ISSUE THREAD

**Issue by Dunkhan** [unvell/ReoGrid#135]
When loading the wpf example project, the scroll behaviour is strange and counterintuitive:

- Scrollbars never reach the end while mousewheel scrolling, they stop at about 0.7 of the way down/across
- Dragging the scrollbar manually with the mouse the last part of the distance does not cause any scrolling
- The view scrolls well outside the limits of the worksheet, showing large areas of white space with no cells

**Comment by jingwood** [comment]
fix #136

**Comment by ottosson** [comment]
I still have this problem.

- "Scrollbars never reach the end while mousewheel scrolling, they stop at about 0.7 of the way down/across"
- "Dragging the scrollbar manually with the mouse the last part of the distance does not cause any scrolling"

**Comment by jingwood** [comment]
Thanks @Dunkhan and @ottosson! This issue now has been fixed and will be released in v2.2.0.
