### ISSUE TITLE
Crash bug

### ISSUE THREAD

**Issue by jingjiajie** [unvell/ReoGrid#138]
When I call AutoFitColumnWidth(), it crashed.
![image](https://user-images.githubusercontent.com/15362382/41819473-90f48770-77f3-11e8-83b3-89f14d336c97.png)

![image](https://user-images.githubusercontent.com/15362382/41819465-7b667440-77f3-11e8-8beb-1044ee783779.png)

**Comment by jingwood** [comment]
Please post the entire exception message.

**Comment by jingjiajie** [comment]
![image](https://user-images.githubusercontent.com/15362382/43311105-035792e4-91bc-11e8-8e54-667090add715.png)

**Comment by jingwood** [comment]
Fixed by #489
