### ISSUE TITLE
unvell.ReoGrid.Drawing.RichText Can't find

### ISSUE THREAD

**Issue by CRREECLEE** [unvell/ReoGrid#139]
unvell.ReoGrid.Drawing contains Text
How can I use the funtion of RichText?
sheet["B2"] = new Drawing.RichText() xxx
The link https://reogrid.net/document/rich-format-text/  no help

**Comment by jingwood** [comment]
You can try the full class name `unvell.ReoGrid.Drawing.RichText`.

**Comment by jingwood** [comment]
Make sure you using the latest version binary, either one of following:

- Downloaded from [ReoGrid webiste](https://reogrid.net/download/)
- Built from latest source code, that can be download from [here](https://github.com/unvell/ReoGrid)
- Installed from [NuGet](https://www.nuget.org/packages/unvell.ReoGrid.dll/)

The source code contains the [RichText](https://github.com/unvell/ReoGrid/blob/master/ReoGrid/Drawing/Text.cs#L51) class, so make sure you are using correct DLL file.
