### ISSUE TITLE
Why I use [delete]  or [drag selection to fill serial] can not trip cellDataChanged or afterCellEdit event? 

### ISSUE THREAD

**Issue by woshixlb** [unvell/ReoGrid#141]
Hi,
    I want to do some acitons after cell data changed, so i regist the AfterCellEdit event, if i double click the cell and text some data, it work okay, but when i  use [delete key] to clear cell or [drag selection to fill serial]  
to append data, it cannot work. How can i solved this problem?(version 2.1)

**Comment by jingwood** [comment]
Did you have tried the `RangeDataChanged` event?

**Comment by woshixlb** [comment]
Thanks for your help. 

I just tried the RangeDataChanged, [delete] action can work, but [drag selection to fill serial] still can not trig the event.

**Comment by jingwood** [comment]
"drag selection to fill serial" will trigger the `CellDataChanged` event, only edit a cell manually trigger the `AfterCellEdit` event.
