### ISSUE TITLE
Import with cell rotation angle not drawing correctly

### ISSUE THREAD

**Issue by BrianShankland** [unvell/ReoGrid#145]
I have a sheet that contains a merged cell rotated 90 degrees.
When I import it is drawn as if no rotation angle is present , even though I can see from internal code breakpoints that your `Cell.Style.RotateAngle = 90`
Have included my Excel sheet as reference, if you need anything further please feel free to contact me.
[BS Main 1.xlsx](https://github.com/unvell/ReoGrid/files/2197218/BS.Main.1.xlsx)

**Comment by jingwood** [comment]
@BrianShankland, just opened your Excel with latest ReoGrid, the rotated text looks fine to me. Have you tried the latest source code?
![rotation-text](https://user-images.githubusercontent.com/3468046/43784490-3b473254-9a9f-11e8-8f3f-3ffb1fe8f686.png)

**Comment by jingwood** [comment]
Fixed by #72
