### ISSUE TITLE
Formula Auto fill programatically

### ISSUE THREAD

**Issue by gamitWeb** [unvell/ReoGrid#148]
Am not getting any thing on how to set formula in a cell and auto fill that formula pragmatically into adjacent cells in same row ? Am missing some thing? any help or example is there.

**Comment by jingwood** [comment]
Just do a normal auto filling pragmatically like:

```csharp
sheet["A2"] = "=A1";
sheet.AutoFillSerial("A2", "B2");
```
The formula of B2 will be `=B1`
