### ISSUE TITLE
[Question] Can you provide a ReoGrid that only include MemoryWorkbook features?

### ISSUE THREAD

**Issue by raytangRT** [unvell/ReoGrid#154]
Hi, 

I am trying to use ReoGrid to do excel file import and export only, but the library requires me to include PresentationFramework,  I can include them for now, but for the future, is it better to separate it into a standalone dll?

Thanks.

**Comment by jingwood** [comment]
`PresentationFramework` is only required by WPF edition, if you have to use only the `MemoryWorkbook`, you may consider to use the Windows Form edition ReoGrid, it doesn't require `PresentationFramework`.

And you can use the minimal configuration build version, that binary file can be downloaded from https://reogrid.net/download, or build from latest source code using the minimal build configuration.

**Comment by raytangRT** [comment]
Hi @jingwood, 

Thanks for the quick reply. 

Are there any chances the minimal version to be published to Nuget?

Thanks

**Comment by jingwood** [comment]
It is not a regular version so I currently have no plan to publish it on NuGet. Thanks.

**Comment by raytangRT** [comment]
Thanks
