### ISSUE TITLE
Error while loading Excel file

### ISSUE THREAD

**Issue by RahulKumarParihar** [unvell/ReoGrid#163]
I am using grd.Load("Path", FileFormat.Excel2007, Encoding.UTF8) where grd is ReoGridControl.
I am still getting _NullReferenceException_ while loading few of the files.
>at unvell.ReoGrid.IO.OpenXML.ExcelReader.AddRunIntoRichText(Document doc, RichText rt, Run r)
at unvell.ReoGrid.IO.OpenXML.ExcelReader.CreateRichTextFromRuns(Document doc, IEnumerable`1 paragraphs)
>at unvell.ReoGrid.IO.OpenXML.ExcelReader.LoadWorksheet(IWorkbook rgWorkbook, Document doc, WorkbookSheet sheetIndex)
>at unvell.ReoGrid.IO.OpenXML.ExcelReader.ReadStream(IWorkbook rgWorkbook, Stream stream)
>at unvell.ReoGrid.Workbook.Load(Stream stream, FileFormat fileFormat, Encoding encoding)
>at unvell.ReoGrid.Workbook.Load(String path, FileFormat fileFormat, Encoding encoding)
>at Excel.LoadDataFromExcel(ReoGridControl grd, String filePath) in d:\ExcelLoadingTool\Loading.cs

**Comment by jingwood** [comment]
I Think this is problem has been fixed. Did you tried the latest source code?
