### ISSUE TITLE
Getting indexes of selected items

### ISSUE THREAD

**Issue by shadrackkibet** [unvell/ReoGrid#167]
I am new to using ReoGrid so this might be a very simple question. I would like to know if it is possible to get selected indexes and store this as a list. If possible how is this done?. I am attaching this screenshot to show my items.
![image](https://user-images.githubusercontent.com/26301973/45924285-31708700-bf05-11e8-954d-91ddb30a7f34.png)

Thanks.

**Comment by ycdaskin** [comment]
You can store them in a list of RangePosition. You can use worksheet's SelectionRangeChanged event to fire the action.

**Comment by jingwood** [comment]
Also the `CellDataChanged` event will returns the index of row and index of column.

The event will be fired when you changed the status of checkboxes.
