### ISSUE TITLE
Reogrid - New Version

### ISSUE THREAD

**Issue by Furgia** [unvell/ReoGrid#169]
I ask you if a new official version of Reogrid is expected in a short time.
Thank you.

**Comment by jingwood** [comment]
Yes, there will be a new release in a short time, thanks.

**Comment by Furgia** [comment]
Good morning.
Are there any news on the release date?
Thank you

**Comment by Furgia** [comment]
Good morning.
 Are there any news on the release date?
 Thank you

**Comment by jingwood** [comment]
Close this since new version has been released.

**Comment by Furgia** [comment]
Good morning.
Where can I find new version ?
In https://reogrid.net/download/ the last version is 2.1 Oct 21, 2017
Thank you

**Comment by jingwood** [comment]
Hi, do you use NuGet? the new package can be installed and updated from NuGet.
https://www.nuget.org/packages/unvell.ReoGrid.dll/

**Comment by Furgia** [comment]
I found version 2.2.0 in NuGet
But it is wpf or winform ?
Thank you

**Comment by Furgia** [comment]
I found https://www.nuget.org/packages/unvell.ReoGridWPF.dll/
Thank you
