### ISSUE TITLE
WPF: Grid displays incorrect values when pasting decimal number into currency cell

### ISSUE THREAD

**Issue by jtattreo** [unvell/ReoGrid#170]
ReoGridControl (v2.1.0) in WPF.

Set your worksheet to auto-format, and one of your columns to currency format. In Excel, create a range of results in a number formatted column:

![image](https://user-images.githubusercontent.com/3751294/46036471-c40a5500-c0c2-11e8-8939-ed3aefcca24e.png)

Now copy this range to the clipboard and paste it into your ReoGrid currency formatted column.  As you can see below, if the value is not a whole number, the grid will change the value being displayed.

![image](https://user-images.githubusercontent.com/3751294/46036582-16e40c80-c0c3-11e8-8820-6e5147d799f9.png)

The cell data itself is correct. It is the formatted result being displayed that is incorrect.

**Comment by ycdaskin** [comment]
It is same with date format. I think reogrid takes "1.10" as October 1st or January 10th depending on your culture settings. I always have to change cell format manually.

**Comment by jingwood** [comment]
I think now it has been fixed, try the latest code.
