### ISSUE TITLE
Scroll troubles when hide/shows rows or columns

### ISSUE THREAD

**Issue by MikhailLavrenov** [unvell/ReoGrid#172]
When reoGridControl have some frozen rows/columns, sheet was scrolled by user to non 0 position, and after call method HideColumns(...) or HideRows(...) or ShowRows(...) or ShowColumns(...) current sheet will be scrolled to 0 position, but scroll bars position stay corectly.
This problem occurs only if control have some frozen rows/columns

**Comment by jingwood** [comment]
similar to #151
