### ISSUE TITLE
Click on frozen cell set sroll bar to 0 position

### ISSUE THREAD

**Issue by MikhailLavrenov** [unvell/ReoGrid#173]
When reoGridControl have some frozen rows/columns,  sheet was scrolled to non 0 position, after click on frozen cell - sheet will be auto scrolled to 0 position

**Comment by jingwood** [comment]
Fixed in https://github.com/unvell/ReoGrid/commit/4a9ef1df4e5428ef4a780e6f7b95f2f9ac6cf9b4, try the latest source code.
