### ISSUE TITLE
Vertical Scroll 

### ISSUE THREAD

**Issue by alejsouza** [unvell/ReoGrid#179]
Hi, 
I wonder if is possible to change any setting to :
When a user use the mouse to select the rows in the grid by clicking on the row number and dragging down, cause the grid to scroll down when the mouse pointer enters the horizontal scroll bar area or out of the grid area (Now it can be done using the mouse wheel)
![7c7ef1ba8b9207ada02db2e5ae714511bbebf450d0a17b2822a4205b4a0cecb3](https://user-images.githubusercontent.com/14909123/46577304-5e6b7200-c9ba-11e8-8f1e-c06ec09b7767.png)

Thanks
Regards

**Comment by jingwood** [comment]
Fixed in https://github.com/unvell/ReoGrid/commit/c07a819e5b43ccd78fb7d591a9aef43676e4f077
