### ISSUE TITLE
Method for trimming empty rows?

### ISSUE THREAD

**Issue by nasheayahu** [unvell/ReoGrid#18]
Hi Jing,

Other than me programmatically skipping empty rows during import, do you have a method for trimming empty rows after the last valid data row?

**Comment by jingwood** [comment]
You can find the valid data row by using property of worksheet:

```c#
var validNumberOfRow = worksheet.MaxContentRow;
```

then set the number of row to remove rows after that
```c#
worksheet.SetRows(validNumberOfRow);
```

**Comment by jingwood** [comment]
Can we close this?
