### ISSUE TITLE
No GridLine for row(0) ?

### ISSUE THREAD

**Issue by Gnuelmpf** [unvell/ReoGrid#181]
Hello there ...
unfortunately I'm not able to get gridlines for row(0).
Any hints ?

![image](https://user-images.githubusercontent.com/43831414/46734394-57cb4c00-cc93-11e8-8595-9df4c4aba609.png)

workaround is to SetRangeBorders for each cell.
:(

**Comment by jingwood** [comment]
If you have cell background color the grid line will not be displayed. You should set borders manually.

**Comment by Gnuelmpf** [comment]
So it's a feature not a bug ! ?
:))
THX Jing

**Comment by jingwood** [comment]
Yes it’s by design. But also it sounds good to add an option that can always show girdlines.
