### ISSUE TITLE
Always empty string with StringifyRange

### ISSUE THREAD

**Issue by Gnuelmpf** [unvell/ReoGrid#183]
Hello,
I always get an empty string after using .StringifyRange().
Where is my problem ?

![image](https://user-images.githubusercontent.com/43831414/46854276-9599b300-ce00-11e8-8478-a7676ac0bee3.png)

Plz help & Thx a lot

**Comment by jingwood** [comment]
It was a bug and now has been fixed. Please try the latest source code. Thanks!
