### ISSUE TITLE
winform Dispose get error

### ISSUE THREAD

**Issue by wu676635990** [unvell/ReoGrid#185]
ReoGrid is used in a  WindowsFormsControlLibrary,   WindowsFormsControlLibrary is used in a winform.
when the winform close, ReoGrid call Dispose function,andthen ReoGrid call the function UpdateViewportControllBounds() to up date , will return an error.

**Comment by wu676635990** [comment]
pitture https://pan.baidu.com/s/17ICq7zldQokpnInNYYc6mQ

**Comment by jingwood** [comment]
How to reappear this?

**Comment by jingwood** [comment]
Similar to #226
