### ISSUE TITLE
ReoGrid Editor rename a dll function

### ISSUE THREAD

**Issue by salvo79** [unvell/ReoGrid#190]
In the editor, for some reason when I add a function that I built in a .dll called ORION5G as an add-in in Excel, when I open the sheet by Reogrid editorwhere the ORION5G formula is found, the]ReoGrid editor renames the function ORION5G by _xll.ORION5G, that is, add the _xll.
Is there any reason in this regard?

**Comment by jingwood** [comment]
It's that Excel renames the custom function during save your .xls file. ReoGrid just read it from .xls file. You can make your custom function name `_xll.ORION5G` in .NET application.
