### ISSUE TITLE
How to multiply value in 100 rows in column A with 100 rows in column B and put the result in Column C

### ISSUE THREAD

**Issue by wmardain** [unvell/ReoGrid#191]
Dear All, 
Can i ask a question here?
I want to multiply values in 100 rows of column A with 100 rows in column B and put the the result in C columns? With just 1 click

I can iterate to sum value of A column.. but i have no idea how to iterate to 100 rows.. and doing multiplication at the same time.

Thanks in advance
Best Regards

**Comment by wmardain** [comment]
I can do it manual. Thanks guys.. it is done now.

Rgds

**Comment by jingwood** [comment]
Set cells data manually, or you can use AutoFill feature:
https://reogrid.net/document/fill-data-serial/
