### ISSUE TITLE
C# ReoGrid performance issue when binding datatable with formula

### ISSUE THREAD

**Issue by karlosRivera** [unvell/ReoGrid#193]
I have populated my data table with random values and formula like =SUM(A1:A2) when there is 150 columns and 4000 rows in datatable then ReoGrid taking approx 20 minute to be populated.

when i am populating ReoGrid without formula then it takes few second to populate ReoGrid but the moment many SUM formulas are being assigned to cell dynamically then ReoGrid take long time to populated.

Here i am sharing my code. so my request please guys see my code logic and tell me is there any flaw when assigning formula to many cell of ReoGrid.

please tell me how could i simplify the logic to populate grid with formula. Is there way to increase the performance of my code with formula as a result ReoGrid can be populated with in few sec or few minute.

Looking for suggestion and guide line. 

**Here is my code**
`
private void btnBindTable_Click(object sender, EventArgs e)
{
    Stopwatch stopwatch = new Stopwatch();
    stopwatch.Start();

    string strSum = "", strColName, strImmediateOneUp = "", strImmediateTwoUp = "";

    int startsum = 0;
    int currow = 0;
    bool firstTimeSum = true;

    int NumRows = 4000;
    int NumColumns = 150;

    var sheet = reoGrd.CurrentWorksheet;
    sheet.Resize(NumRows, NumColumns);  // resize 

    DataTable dt = new DataTable();

    for (int col = 0; col < NumColumns; col++)
    {
        strColName = GenerateColumnText(col);
        DataColumn datacol = new DataColumn(strColName, typeof(string));
        dt.Columns.Add(datacol);
    }

    for (int row = 0; row < NumRows; row++)
    {
        dt.Rows.Add();

        for (int col = 0; col < NumColumns; col++)
        {
            if (row < 2)
            {
                dt.Rows[row][col] = new Random().Next(1, NumRows).ToString("D2"); 
            }
            else
            {
                if (firstTimeSum)
                {
                    if (row - currow == 2)
                    {
                        currow = row;
                        startsum = 0;
                        firstTimeSum = false;
                    }
                    else
                    {
                        startsum = 1;
                    }
                }
                else
                {
                    if (row - currow == 3)
                    {
                        currow = row;
                        startsum = 0;
                    }
                }

                if (startsum == 0)
                {
                    strColName = GenerateColumnText(col);
                    strImmediateOneUp = strColName + ((row + 1) - 1).ToString();
                    strImmediateTwoUp = strColName + ((row + 1) - 2).ToString();
                    dt.Rows[row][col] = strSum; 

                    string cellname = GenerateColumnText(col) + (row + 1).ToString();
                    var cell = sheet.Cells[cellname];
                    cell.Style.BackColor = Color.LightGoldenrodYellow;
                }
                else
                {
                    dt.Rows[row][col] = new Random().Next(1, NumRows).ToString("D2"); 
                }
            }

        }

        startsum = 1;
    }

    sheet["A1"] = dt;

    stopwatch.Stop();
    TimeSpan timeSpan = stopwatch.Elapsed;

    MessageBox.Show(string.Format("Time elapsed: {0}h {1}m {2}s {3}ms", timeSpan.Hours, timeSpan.Minutes, timeSpan.Seconds, timeSpan.Milliseconds));

}`
Thanks

**Comment by jingwood** [comment]
Closed because of duplication issue from https://github.com/unvell/ReoGrid/issues/194
