### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by fredatgithub** [unvell/ReoGrid#2]
Hello Jing,
It would be a great idea to add samples on Releases Tab.

**Comment by jingwood** [comment]
OK, but where is Release Tab?

**Comment by fredatgithub** [comment]
Here:
[Here you can post any document, binary, sample, demo](https://github.com/unvell/ReoGrid/releases)

**Comment by jingwood** [comment]
Your page looks nice, let me add some descriptions.
