### ISSUE TITLE
ColumnHeaderCollection is NOT a Collection ?

### ISSUE THREAD

**Issue by Gnuelmpf** [unvell/ReoGrid#206]
Hello Jing,
I'm not sure if it's a bug or just wrong code.

![image](https://user-images.githubusercontent.com/43831414/49510344-36986d80-f888-11e8-9593-3b10345244cf.png)

**Comment by jingwood** [comment]
Added enumerable support https://github.com/unvell/ReoGrid/commit/123c6d69ac180559ebf196244c9dfb4f4322ed62
thanks.
