### ISSUE TITLE
CommitRunAndCreateNode skips ;

### ISSUE THREAD

**Issue by vinnik-dmitry07** [unvell/ReoGrid#207]
`private static readonly Regex TokenRegex = new Regex(
			"\\s*((?<string>\"(?:\"\"|[^\"])*\")|(?<union_ranges>[A-Z]+[0-9]+:[A-Z]+[0-9]+(\\s[A-Z]+[0-9]+:[A-Z]+[0-9]+)+)"
			+ "|(?<range>\\$?[A-Z]+\\$?[0-9]*:\\$?[A-Z]+\\$?[0-9]*)"
			+ "|(?<cell>\\$?[A-Z]+\\$?[0-9]+)"
			+ "|(?<token>-)|(?<number>\\-?\\d*\\"
			+ System.Threading.Thread.CurrentThread.CurrentCulture.NumberFormat.NumberDecimalSeparator + "?\\d+)"
			+ "|(?<true>(?i)TRUE)|(?<false>(?i)FALSE)|(?<identifier>\\w+)"
			+ "|(?<token>\\=\\=|\\<\\>|\\<\\=|\\>\\=|\\<\\>|\\=|\\!|[\\=\\.\\,\\+\\-\\*\\/\\%\\<\\>\\(\\)\\&\\;\\^]))", // <- here is not System.Threading.Thread.CurrentThread.CurrentCulture.TextInfo.ListSeparator
			RegexOptions.Compiled);
`
Debug It by breakpoint on 308, 622 lines of Parser.cs.

**Comment by jingwood** [comment]
Hi @vinnik-dmitry07, thanks for your information! 

Now it has been fixed in #392.
