### ISSUE TITLE
Error on Load File: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by Jozelom** [unvell/ReoGrid#212]
Good morning, I am loading a file and I get the following error:
![image](https://user-images.githubusercontent.com/38925156/50098019-1dc57b80-01e9-11e9-807b-e624790ac6cf.png)
The loading code is
![image](https://user-images.githubusercontent.com/38925156/50098234-86145d00-01e9-11e9-96ea-2a471b5ffb69.png)

The file was created with ClosedXML.Report (which can be opened in excel)

If open and save the file with excel, reogrid opens it without problems

The edition that I use is winforms
If anyone has had this problem and has solved it, help me, thanks

**Comment by jingwood** [comment]
Thanks! Seems ClosedXML.Report produces xlsx file that doesn't include a dimension of worksheet. This problem can be improved.

**Comment by jingwood** [comment]
I think this has been resolved by #292. If there still the problem please let me know. Thanks!
