### ISSUE TITLE
抛出异常：System.Collections.Generic.KeyNotFoundException:“给定关键字不在字典中。”

### ISSUE THREAD

**Issue by realZhangChi** [unvell/ReoGrid#213]
我要加载的表格是格式比较复杂的，涉及到多个合并后的单元格，与多种格式。
请问这是什么原因产生的异常，应该如何进行处理？谢谢！
这是异常信息：
在 MS.Internal.FontCache.FontFaceLayoutInfo.IntMap.System.Collections.Generic.IDictionary<System.Int32,System.UInt16>.get_Item(Int32 i)
   在 unvell.ReoGrid.Drawing.Text.Run.AppendText(String text)
   在 unvell.ReoGrid.Drawing.Text.Paragraph.AddText(String text, String fontName, Nullable`1 fontSize, Nullable`1 fontStyles, Nullable`1 textColor, Nullable`1 backColor)
   在 unvell.ReoGrid.IO.OpenXML.ExcelReader.AddRunIntoRichText(Document doc, RichText rt, Run r)
   在 unvell.ReoGrid.IO.OpenXML.ExcelReader.CreateRichTextFromRuns(Document doc, IEnumerable`1 paragraphs)
   在 unvell.ReoGrid.IO.OpenXML.ExcelReader.LoadWorksheet(IWorkbook rgWorkbook, Document doc, WorkbookSheet sheetIndex)
   在 unvell.ReoGrid.IO.OpenXML.ExcelReader.ReadStream(IWorkbook rgWorkbook, Stream stream)
   在 unvell.ReoGrid.Workbook.Load(Stream stream, FileFormat fileFormat, Encoding encoding)
   在 unvell.ReoGrid.Workbook.Load(String path, FileFormat fileFormat, Encoding encoding)
   在 unvell.ReoGrid.ReoGridControl.Load(String path, FileFormat fileFormat)
   在 QZ.ImportExcel.Universal.UI.MultipersonExcel.OpenFolderBtn_Click(Object sender, RoutedEventArgs e) 位置 D:\Visual Studio\2017\source\repos\QZ.ImportExcel.Universal\QZ.ImportExcel.Universal\MultipersonExcel.xaml.cs:行号 49
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   在 System.Windows.Controls.Button.OnClick()
   在 System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   在 System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   在 System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   在 System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   在 System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   在 System.Windows.Input.InputManager.ProcessStagingArea()
   在 System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   在 System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   在 System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   在 System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Boolean isSingleParameter)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Boolean isSingleParameter, Delegate catchHandler)
   在 System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Boolean isSingleParameter)
   在 MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   在 MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   在 System.Windows.Threading.Dispatcher.TranslateAndDispatchMessage(MSG& msg)
   在 System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   在 System.Windows.Application.RunInternal(Window window)
   在 QZ.ImportExcel.Universal.UI.App.Main()

**Comment by realZhangChi** [comment]
我更换了字体之后发现可以了，是否是字体支持问题，抛异常的字体是“方正小标宋简体”。由于一些原因，我只能在软件中适配字体，而不能更改xlsx文件。请问有没有解决方案，万分感谢！

**Comment by jingwood** [comment]
Please post your issue in English.

**Comment by realZhangChi** [comment]
> Please post your issue in English.

I'm sorry!When I use the "Load" method to Load the table and display it, the method throws this exception.After I changed the font in the table, it can be displayed normally.But for some reason I don't have permission to change the excel file.Is there any other way to solve this problem?Thank you very much!

**Comment by jingwood** [comment]
This problem may been fixed in latest source? Did you try the latest source code?

**Comment by chencun** [comment]
> This problem may been fixed in latest source? Did you try the latest source code?

How soon is the next official release?With version 2.1, fonts are also problematic to load dynamically.put it in a usercontrol and then dynamically load usercontrol to theTtabcontrol ,Unable to load font, default font will be used.

**Comment by realZhangChi** [comment]
> This problem may been fixed in latest source? Did you try the latest source code?

I'm using version 2.1, which has this problem.In which version has this problem been fixed?
