### ISSUE TITLE
How to prevent formula being execute after datatable bind

### ISSUE THREAD

**Issue by tzacksindia** [unvell/ReoGrid#214]
i have datatable which has many formula like `=SUM(A1:A10)`

after datatable bind reogrid take long time because i guess it is evaluating formula in every cell.

this way i bind my datatable to reogrid
```
var sheet = dgvReport.CurrentWorksheet;
sheet.SuspendFormulaReferenceUpdates();
var sheet = dgvReport.CurrentWorksheetsheet["A1"] = dtMain;
sheet.ResumeFormulaReferenceUpdates();
```

please tell me what code i need to run as a result after reogrid bind formula will not execute and also tell me function name which i would call to evaluate formula after datatable bind.

looking for suggestion. thanks

**Comment by jingwood** [comment]
You can try the `worksheet.Recalculate` method.

**Comment by jingwood** [comment]
Sorry for reply so late. You can reopen this anytime if you still have questions or problems.
