### ISSUE TITLE
ButtonCell style

### ISSUE THREAD

**Issue by fredericoregateiro** [unvell/ReoGrid#216]
I need to style the ButtonCell.
How can i change the button background and border?

**Comment by jingwood** [comment]
ReoGrid draws the button use standard .NET library, it cannot be styled. 

1. You can draw your own button by using `CellBody` class. See [Custom cell](https://reogrid.net/document/custom-cell/) 

2. Use ImageButton, just create your button as image. See [Built-in cell types](https://reogrid.net/document/built-in-cell-types/)
