### ISSUE TITLE
Finding the Minimum WPF DLL

### ISSUE THREAD

**Issue by steven11980** [unvell/ReoGrid#219]
Our company would like to use the ReoGrid-2.1.0.0-WPFMinimum release that the Github source generates under CFG=Minimum, the company build process is such that it is easier to integrate third party components via nuget, but we are worried that the only releases we see on nuget.org are the following packages:

PM> Find-package unvell

Id                                  Versions                                 Description                                                       
--                                  --------                                 -----------                                                       
unvell.ReoGrid.dll                  {2.1.0}                                  Free Spreadsheet control to open, show, edit, print and save Ex...
unvell.ReoGridWPF.dll               {2.1.0}                                  Free Spreadsheet control to open, show, edit, print and save Ex...
Time Elapsed: 00:00:04.3904394

When we compare the binaries within the nuget package to the binary release that is produced when CFG=Minimum, generates ReoGrid-2.1.0.0-WPFMinimum, we see that the sizes of the binary are different.

**Comment by jingwood** [comment]
Currently only standard editions available on NuGet, you can also download all editions from https://reogrid.net/download
