### ISSUE TITLE
Using Worksheet with each cell

### ISSUE THREAD

**Issue by segunodu** [unvell/ReoGrid#22]
Hello, I have 3 worksheets (gold, silver, copper) and I am setting the same formula "=SUM(C3:D3)" for the same cell F2. Instead of writing:

gold["F2"] = "=SUM(C3:D3)";
sliver["F2"] = "=SUM(C3:D3)";
copper["F2"] = "=SUM(C3:D3)";

Is it not possible to write:

object[] workbook = { gold["F2"], silver["F2"], copper["F2"] };

string formula = "=SUM(C3:D3)";

foreach (object sheet in workbook )
{
      sheet = formula;
}

I have tried using this and for() but it is not working or am I missing a cast?
Thank you

**Comment by jingwood** [comment]
Use the code like this:
```csharp
var sheet1 = workbook.NewWorksheet();
var sheet2 = workbook.NewWorksheet();
var sheet3 = workbook.NewWorksheet();

var cells = new Cell[] { sheet1.Cells["F2"], sheet2.Cells["F2"], sheet3.Cells["F2"] };

foreach (var cell in cells)
{
  cell.Formula = "SUM(C3:D3)";
}
```

**Comment by segunodu** [comment]
Thank you very much, jingwood. It worked.
