### ISSUE TITLE
How to check if worksheet is empty

### ISSUE THREAD

**Issue by LaraSQP** [unvell/ReoGrid#221]
As the title reads, how does one check if a worksheet is empty?

I am aware of `IsWorkbookEmpty` but I am interested in a given sheet, such as the `CurrentWorksheet`.

Thank you, guys.

**Comment by jingwood** [comment]
You may use `MaxContentRow` and `MaxContentCol`. Zero means no content on the worksheet. But notice that this doesn't work if content removed from a worksheet.

**Comment by LaraSQP** [comment]
Much appreciated.

And a heartfelt thank you to all those involved in the development and support of ReoGrid.

Amazing work.
