### ISSUE TITLE
WPF Reogrid Crash on Keypress from thrown System.IndexOutOfRangeException in unvell.Reogrid 2.1.0.0

### ISSUE THREAD

**Issue by IrisPeter** [unvell/ReoGrid#223]
**Describe the bug**
We are using the Spreadsheet to preview an Excel Spreadsheet and as such we don't want the user to have the ability to edit any of the cells.  However we do want the user to be able to access our special right-click menu.

To do this we introduced a LockdownGrid method and we set the following properties:

    grid.Readonly = true;
    grid.SheetTabNewButtonVisible = false;
    grid.AllowDrop = false;
    var worksheet = grid.CurrentWorksheet;
    worksheet.DisableSettings(WorksheetSettings.Edit_AllowAdjustRowHeight);
    worksheet.DisableSettings(WorksheetSettings.Edit_AllowAdjustColumnWidth);
    worksheet.EnableSettings(WorksheetSettings.Edit_Readonly);
    worksheet.SelectionMode = WorksheetSelectionMode.None;

One of my first attempts to make the Spreadsheet non-modifiable the property I tried disabled all events so I could no longer access a right-click menu 

However if the user presses any key on the keyboard then an System.IndexOutOfRangeException is thrown this is because there is no selection present.  

The  code goes into Worksheet.StartEdit and finds out that the cell is invalid because both row and column are -1, and so goes into GetMergedCellOfRange, and the row and column are passed over to  CreateAndGetCell and then because the arguments passed are still invalid, and it tries to index into the cells array this is the point at which the IndexOutOfRangeException is thrown.

The error is actually thrown from the Index4DArray<T> constructor

**To Reproduce**
1. Create a WPF project
2. Add reogrid to the MainWindow
3. Press a key

**Expected behavior**
Nothing should happen because no cell has been selected and the grid ReadOnly property was set

**Workaround**
Set worksheet.FocusPos to a cell, which allows BeforeCellKeyDown to fire, and then when it does you can set e.IsCancelled to true

**Edition**
Which edition of ReoGrid do you using?
 - WPF

**Environment (please complete the following information):**
 - Windows 10
 - Language of OS: English

**Comment by jingwood** [comment]
Fixed in latest source code. Thanks for report!
