### ISSUE TITLE
Copy/paste formulas to/from Excel

### ISSUE THREAD

**Issue by LaraSQP** [unvell/ReoGrid#224]
As the title reads, is it possible to copy/paste formulas to/from Excel?

I can do shown values no problem. But formulas and unformatted values get lost in the clipboard.

Saving to file and opening in Excel works fine. This is only the clipboard.

Thank you, guys.

**Comment by jingwood** [comment]
It is impossible and I think it's a difficult task.

**Comment by LaraSQP** [comment]
I understand. Thanks again.
