### ISSUE TITLE
Can't undo fill serial

### ISSUE THREAD

**Issue by ottosson** [unvell/ReoGrid#229]
When I use the fill data serial and want to undo it, the fill event is not registered to the list of previous events and whatever I did before the fill serial will be undone instead.

**To Reproduce**
![reogrid_undo_demo](https://user-images.githubusercontent.com/3355320/54757738-244dff80-4beb-11e9-9529-06651d1906ef.gif)

**Expected behavior**
The fill serial should be undone

**Edition**
Which edition of ReoGrid do you using?
 - WPF

**Environment (please complete the following information):**
Windows 10 - Language of OS: English

**Comment by jingwood** [comment]
wip to fix, #233

**Comment by jingwood** [comment]
Fixed. Please use latest source code.

**Comment by ottosson** [comment]
I was too quick to close this issue. It seems the undo removes the value of the cells:

![reogrid_undo2_demo](https://user-images.githubusercontent.com/3355320/54999382-60f56e80-4fd0-11e9-831d-37bf0f30a280.gif)

**Comment by jingwood** [comment]
Fixed again.

**Comment by ottosson** [comment]
Much better 👍 Thanks!
