### ISSUE TITLE
Why {AfterCellEdit} & {CellDataChanged} events trigger Radio Button {click} event?

### ISSUE THREAD

**Issue by tzengshinfu** [unvell/ReoGrid#23]
Hi,
There are two controls, ReoGrid and Radio Button on a form.
I input some text and press [Enter] key on ReoGrid,
it will trigger Radio Button [click] event.
(both [AfterCellEdit] & [CellDataChanged] events trigger)

how can I resolve this problem?

**Comment by jingwood** [comment]
What's the problem?

**Comment by tzengshinfu** [comment]
Hi, Jing:

The problem(ReoGrid triggers Radio button [click] event) 
is happening in my colleague's project.

I suggested she to use ReoGrid instead of Excel VBA.

I am trying to reproduce her case, **but nothing happend**.

Her project is complex and she creates controls dynamically.

So please close this issue, I told her to post this problem herself late. Thank you.

**Comment by tzengshinfu** [comment]
Hi, Jing:

The problem(ReoGrid triggers Radio button [click] event)
is happening in my colleague's project.

I suggested she to use ReoGrid instead of Excel VBA.

I am trying to reproduce her case, but nothing happend.

Her project is complex and she creates controls dynamically.

So I close this issue and told her to post this problem herself late. Thank you.
