### ISSUE TITLE
How can I update my current version with the changes on here?

### ISSUE THREAD

**Issue by cnmorgan** [unvell/ReoGrid#232]
This is less a bug report and more just a question. I started using the latest release version for my program, but the bug I reported earlier (about readonly not being able to be set to false) has caused me some problems. It seems that it has been fixed in the code on here, but I'm not sure how to go about updating the components I'm using with the fixes.

**Comment by ottosson** [comment]
Download the source code
Run build-release.bat
Check _Output for your version

**Comment by cnmorgan** [comment]
What do you mean by Check_Output? is that a directory? or is it a command I need to use?

**Comment by ottosson** [comment]
Yes, for clarity sake and if anyone else is having the same question, _Output is a folder in the project folder that's created when you build the project with build_release.bat.
