### ISSUE TITLE
Reogrid slow setting style backcolor

### ISSUE THREAD

**Issue by basyr** [unvell/ReoGrid#237]
Hi,

We're trying the reoGrid .NET control in our application.
In the grid, we have 25 columns and 75 rows.
It's a sort of calendar. 
Now we have to set the backcolor for some cells (can be up to 200 cells). All different colors.
But running this functionality is very slow. It can take up to 10 seconds.
We can't take a range to speed up.
So how can this get running faster ? 
I'm using sheet.cells[cell].styles.backcolor = ….

Regards
Bart

**Comment by jingwood** [comment]
Post some code or upload a project that shows your problem.

**Comment by basyr** [comment]
Meanwhile find out how to speed up.
Using sheet.range instead of sheet.cells goes much faster
