### ISSUE TITLE
Reogrid slow when loading

### ISSUE THREAD

**Issue by segunodu** [unvell/ReoGrid#24]
Hello Jingwood, I have 9 worksheets in reogrid workbook and each sheet has 4120 cells with formulas in them which means 37,080 cells with formulas in the whole workbook.
Whenever I load the program, it takes 32 minutes 25 seconds for the program to come up. Is there a way I can speed up reogrid view when loading because no  one will like that kind of program.
Thank you.

**Comment by jingwood** [comment]
It looks not normal. If your formulas use feature that ReoGrid doesn't support, ReoGrid will throw exceptions and output the debug information in console for every errors, which is very slow. 

Try run your program with Release build configuration. Is it faster?

**Comment by segunodu** [comment]
Thank you very much

**Comment by segunodu** [comment]
var sheet1 = workbook.NewWorksheet();
            var sheet2 = workbook.NewWorksheet();
            var sheet3 = workbook.NewWorksheet();
            var cells = new Cell[] { sheet1.Cells["F2"], sheet2.Cells["F2"], sheet3.Cells["F2"] };

            for (int i = 0; i <= cells.Length; i++)
            {
                cells[i] = "SUM(C3:D3)";
            }

**Comment by segunodu** [comment]
Hello Jingwood, the foreach loop is the main reason my program using reogrid is slow in loading. So I would like to know if for loop can be used. I tried the code below, the program compiles but it does not load.

            var sheet1 = workbook.NewWorksheet();
            var sheet2 = workbook.NewWorksheet();
            var sheet3 = workbook.NewWorksheet();

            var cells = new Cell[] { sheet1.Cells["F2"], sheet2.Cells["F2"], sheet3.Cells["F2"] };

            for (int i = 0; i <= cells.Length; i++)
            {
                cells[i] = "SUM(C3:D3)";
            }
 Thank you.

**Comment by jingwood** [comment]
I don't see any problems from your code. `for` loop itself doesn't slow down loading process, it must be other reason. 

A normal `for` loop to set cells data, for 100000 rows, it takes less than 1 second.

```csharp
for (int i = 0; i < worksheet.RowCount; i++)
{
	worksheet[i, 1] = (i + 1);
}
```

**Comment by segunodu** [comment]
I read a document on Performance Tips and Tricks in .NET Applications
[(https://msdn.microsoft.com/en-us/library/ms973839.aspx)] where it says 

>  The JIT is smart enough (in many cases) to optimize away bounds-checking and other things inside a For loop, but is prohibited from doing this on foreach walks

Thank you so much for the code

**Comment by segunodu** [comment]
Hello Jing, I have tried the code you suggested but I am still not getting anything.

for (int i = 0; i < worksheet.RowCount; i++)
{
	worksheet[i, 1] = (i + 1);
        cells[i] = "SUM(C3:D3)";
}

**Comment by segunodu** [comment]
This is want I want to do. 

            var testGrid = testGridControl;
            var sheet1 = testGrid.NewWorksheet();
            var sheet2 = testGrid.NewWorksheet();
            var sheet3 = testGrid.NewWorksheet();
            var sheet4 = testGrid.NewWorksheet();
            var testCell = new Cell[] { sheet1.Cells["D2"], sheet2.Cells["D2"], sheet3.Cells["D2"], sheet4.Cells["D2"] };


Instead of using foreach loop:
            foreach(var tCell in testCell)
            {
                tCell.Formula = "=SUM(A2:C2)";
            }

I want to use for loop or something that looks like this:
            for(int i = 0; i <= testCell.Length; i++)
            {
                testCell[i].Formula = "=SUM(A2:C2)";
            }
I have tried this but it is not working. I would like if you could explain the for loop code you gave me.

Thank you.

**Comment by segunodu** [comment]
I have found the problem that made Reogrid slow, I put the sample data I used to check the function calculations after the code for the calculations instead of before it. It made the Reogrid very slow. On its own, Reogrid is very fast when loading data. Sorry for the trouble.
Thank you.

**Comment by 3Bubble** [comment]
when set cell content like below, **it loads very slow**, like 20s for 100+ numbers .  
`for (int row = 0; row < dt.Rows.Count; row++)
                {
                    for (int col = 0; col < dt.Columns.Count; col++)
                    {
                        sheet[row, col] = val;
                    }
                }`
