### ISSUE TITLE
is it possible that input a cell reference in a cell then input another text value?

### ISSUE THREAD

**Issue by hyzhang** [unvell/ReoGrid#247]
for example, A1's value is `abc`, in A2 there's a formula, `=A1`, now A2's value is `abc` too, is it possible that I input another value e.g. `def` into `A2`, but keeps the original formula `=A1` please?

**Comment by jingwood** [comment]
To do that you may have to handle the `CellDataChanged` event and restore the formula to `=A1` by yourself when A2's data is changed.
