### ISSUE TITLE
Worksheet's event RowsInserted not launched when calling InsertRows at the end

### ISSUE THREAD

**Issue by zillemarco** [unvell/ReoGrid#249]
When calling `InsertRows` on a worksheet specifing to add the rows at the end (`worksheet.InsertRows(worksheet.RowCount, 1)` for example) the event `RowsInserted` is not sent.

Looking at the code this is due to the fact that when `InsertRows` is called specifing the last row as the index to insert new rows, it falls back to `AppendRows`, which doesn't launch the event `RowsInserted`.

This is using Windows Form version of ReoGrid 2.1.0.0 on Windows 10.

**Comment by jingwood** [comment]
Fixed. Please use the latest source code.
