### ISSUE TITLE
Problem with filling spreadsheet with datatable

### ISSUE THREAD

**Issue by tzengshinfu** [unvell/ReoGrid#25]
Hi Dear ReoGrid support: 

I followed this article https://reogrid.net/faq/fill-grid-with-datatable/
then I got a error 
![image_20170710101332](https://user-images.githubusercontent.com/2170033/28000740-72d4de86-655a-11e7-9c8c-9fb411a980ee.png)

my code:
            `this.gradeInformationTableAdapter.Fill(this.pLGDW01.GradeInformation);`
            `DataTable dt = gradeInformationTableAdapter.GetData();`
            `//reoGridControl1.CurrentWorksheet["A1"] = dt;`
            `reoGridControl1.CurrentWorksheet.SetRangeData("A1", dt);`

**Comment by jingwood** [comment]
SetRangeData should be fixed. Try this:

```csharp
sheet.Resize(dt.Rows.Count, dt.Columns.Count);
sheet["A1"] = dt;
```

**Comment by tzengshinfu** [comment]
Hi, Jing:

It's still happeing.😵

![error](https://user-images.githubusercontent.com/2170033/28064016-b52376f6-6665-11e7-8062-ddf30935f6bf.png)

my code:
`this.gradeInformationTableAdapter.Fill(this.pLGDW01.GradeInformation);`
`DataTable dt = gradeInformationTableAdapter.GetData();`
`reoGridControl1.CurrentWorksheet["A1"] = dt;`

**Comment by tzengshinfu** [comment]
Hi, Jing:

I write it with "traditional method"
(open connection→use command→load datatable, It's ok now.

**Comment by jingwood** [comment]
Nice! thanks.
