### ISSUE TITLE
Formula SyntaxError using IF

### ISSUE THREAD

**Issue by Vladimir0184** [unvell/ReoGrid#253]
With a formula using IF, the error "SyntaxError" occurs.
For example, the formula: `IF(A1>0, A2/A1,0)` will be in error.
And the formula `IF (A1>0,A2/A1, 0)` will be without error. The difference lies in the presence of a space in front of the zero at the end of the formula for the case of a false condition.

**Comment by jingwood** [comment]
I tested the case you mentioned, I can't find any problem. Is there any other stuff that affects the result? It will be helpful if you save your worksheet as .RGF file and upload to here.
![image](https://user-images.githubusercontent.com/3468046/60271075-a0fc2280-992c-11e9-9bdb-60d648cfe532.png)

**Comment by Vladimir0184** [comment]
Sorry for not answering for so long. I could not save the example in the RGF format, since the erroneous formula is simply not preserved. But I tried to save it in the xlsx format, which I then need to open using ReoGridEditor.
[if_formula.xlsx](https://github.com/unvell/ReoGrid/files/3353621/if_formula.xlsx)
![img1](https://user-images.githubusercontent.com/29650966/60569664-8a185e80-9d78-11e9-94c7-de4a5abbe3ac.JPG)
![img2](https://user-images.githubusercontent.com/29650966/60569686-943a5d00-9d78-11e9-8c52-d08b9752a917.JPG)

**Comment by Vladimir0184** [comment]
If I fill the grid from the code, then the formula with IF does not work

**Comment by yamidcelta** [comment]
Nice, that tip works for me, separate the comma with spaces, thank you.

**Comment by jingwood** [comment]
Fixed by #392
