### ISSUE TITLE
跨表公式计算问题

### ISSUE THREAD

**Issue by Ramon403** [unvell/ReoGrid#26]
Formula:
=SUM(Sheet2!A1:A10)            Why couldn't calculated the result
上面的公式为什么不能计算出结果？ 计算结果为0
但是如果我在公式单元格所在的Sheet表的A1-A10的单元格填值，则会求和，也就是不支持跨表公式计算么？ 但是我在调试源码的时候，发现公式是解析出了Sheet2表的， 这是不是BUG？

**Comment by jingwood** [comment]
Please post your question in English, thanks.

**Comment by XLCYun** [comment]
是不是给下代码和表格内容会好一些？

**Comment by tan133** [comment]
Ramon403 commented on 11 Jul 2017 
Formula:
=SUM(Sheet2!A1:A10) Why couldn't calculated the result
use this in sheet1 ,it can get result,show 0 only
and use in the same sheet ,it can work
when i debug it ,i find that code is find sheet2 correct , ,is this a bug?

**Comment by tan133** [comment]
XLCYun commented on 21 Aug 2017 
sir ,document  ,can you show code in your website 
ps:i find it ,you don't find it????
