### ISSUE TITLE
[Question]How to get the data range? Or how to remove all empty rows and columns?

### ISSUE THREAD

**Issue by Flithor** [unvell/ReoGrid#260]
I want to use ReoGrid to display the excel file without editing.
But after the file opened and displaying, there will has 200 rows and colums by default of ReoGrid.
How can I get the all of the data range, or how to remove all empty rows and columns?

**Comment by Eireannanl** [comment]
As far as I know, you can set number of rows and columns with code like this.
```
var sheet = reoGridControl1.CurrentWorksheet;
sheet.SetRows( [amount you want] );
sheet.SetCols( [amount you want] );
```

**Comment by Flithor** [comment]
But **I don't know**
That's why I ask this question.

**Comment by jingwood** [comment]
Not sure what are you want to do, but when you load an Excel file all existing worksheets will be removed automatically, you don't need to remove them. 

And ReoGrid doesn't allow to remove all rows and columns from a worksheet, you have to keep a worksheet has at least one cell (1x1 grid).

If you want to set the numbers of cell, use the method @Eireannanl mentioned. Or you can use `Resize` method:

```cs
sheet.Resize(1, 1)
```

If you want to know how many rows and columns on worksheet, use `sheet.Rows.Count` method. To know how many rows or columns contains data, check `sheet.MaxContentRow` property.
