### ISSUE TITLE
How to set the formula bar

### ISSUE THREAD

**Issue by pitetow** [unvell/ReoGrid#267]
Thank you very much for answering my question.

Since the document does not mention setting the formula bar, this problem has plagued me for 2 days.

I hope to get your guidance.

**Comment by jingwood** [comment]
@pitetow formula bar is not a standard component included in ReoGrid. In Editor there is a formula bar component provided just for easy to use ReoGrid. If you want to make a formula bar, you have to create your own, of course you can copy code of formula bar from this repository and build on it.
