### ISSUE TITLE
 when it exceeds 1000 rows, SetRangeData take too long time

### ISSUE THREAD

**Issue by mazh3000** [unvell/ReoGrid#268]
sheet.SetRangeDataFormat(0, 0, 1000,1, CellDataFormatFlag.Text)     take too long time

**Comment by jingwood** [comment]
In my environment, it takes only **73ms**.

Test code:
```cs
var sheet = this.grid.CurrentWorksheet;

var sw = Stopwatch.StartNew();

sheet.SetRows(2000);

for (int i = 0; i < 1000; i++)
{
	sheet[i, 0] = "123456";
}

sheet.SetRangeDataFormat(0, 0, 1000, 1, CellDataFormatFlag.Text);

sw.Stop();

MessageBox.Show(sw.ElapsedMilliseconds + "ms");
```

![image](https://user-images.githubusercontent.com/3468046/63081880-b7634980-bf7f-11e9-8867-f423005c5014.png)

and **154ms** for **10000 rows**.

There should be other reason to make ReoGrid slow in your environment, try post more information.
