### ISSUE TITLE
Date Sorting Bug

### ISSUE THREAD

**Issue by necrohunter** [unvell/ReoGrid#27]
Hi,
I am filling one row with dates from an SQL database. SQL date format is "date" and it is like this in the SQL Server 2016-02-22 but in visual studio it is `22.09.2018`. I use this code to format the cells : `22.09.2018`

```csharp
sheet.SetRangeDataFormat("F2:F200", unvell.ReoGrid.DataFormat.CellDataFormatFlag.DateTime, 
    new unvell.ReoGrid.DataFormat.DateTimeDataFormatter.DateTimeFormatArgs
            {

                CultureName = "tr-TR",
                // CultureName = "en-GB",
                Format = "dd.MM.yyyy"
            });
```
and this code to sort: 
```csharp
sheet.SortColumn(5, "A2:U" + (sipIndex-1).ToString(), unvell.ReoGrid.SortOrder.Ascending);
```

it doesn't sort by itself i almost try every combination. It only works when i individually click all date cells twice and then press the sort button for sorting. Can you know anything about this problem and how can i solve it? 
Thank you for your help in this matter.

**Comment by jingwood** [comment]
What is type of data that is set into cells using date format? If the data is string type, sort will not be performed correctly. You may have to convert the string "22.09.2018" into `DateTime` type and set the date time value into cells.

You can parse the string by using `DateTime.parseExact` method.

**Comment by necrohunter** [comment]
Thank you very much i really appreciate it. It resolved quickly with your help. I copied the data from database to a Datetime object not a string, then i set that data into cells it sorted like a charm. Thank you very much for your help again i really like the api.
