### ISSUE TITLE
Non-English Versions of Windows

### ISSUE THREAD

**Issue by ajayre** [unvell/ReoGrid#278]
Here is the bug fix for languages that use comma as a decimal separator:

`        private static readonly Regex TokenRegex = new Regex(
            "\\s*((?<string>\"(?:\"\"|[^\"])*\")|(?<union_ranges>[A-Z]+[0-9]+:[A-Z]+[0-9]+(\\s[A-Z]+[0-9]+:[A-Z]+[0-9]+)+)"
            + "|(?<range>\\$?[A-Z]+\\$?[0-9]*:\\$?[A-Z]+\\$?[0-9]*)"
            + "|(?<cell>\\$?[A-Z]+\\$?[0-9]+)"
            + "|(?<token>-)|(?<number>\\-?\\d*\\"
            + System.Threading.Thread.CurrentThread.CurrentCulture.NumberFormat.NumberDecimalSeparator + "?\\d+)"
            + "|(?<true>(?i)TRUE)|(?<false>(?i)FALSE)|(?<identifier>\\w+)"
            + "|(?<token>\\=\\=|\\<\\>|\\<\\=|\\>\\=|\\<\\>|\\=|\\!|[\\=\\." + System.Threading.Thread.CurrentThread.CurrentCulture.TextInfo.ListSeparator + "\\+\\-\\*\\/\\%\\<\\>\\(\\)\\&\\^]))",
            RegexOptions.Compiled);
`

**Comment by jingwood** [comment]
Thanks! Applied in #392.
