### ISSUE TITLE
Get default colors

### ISSUE THREAD

**Issue by ciahua** [unvell/ReoGrid#279]
**Is your feature request related to a problem? Please describe.**
How to get the default colors of the sheet, such as cell border's color...
I could not get the color from "GetRangeBorders" (all 0 values) if not setting in advance. But I need the default border color without setting...

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by yujiaocao** [comment]
why ReoGrid don't support .netframework4.7 ?

**Comment by jingwood** [comment]
Hi @ciahua 
You can use `ControlAppearanceStyle.CreateDefaultControlStyle()` method to get default border color. There are also other default colors can be found.
See https://reogrid.net/document/control-appearance/

Hi @yujiaocao 
What do you mean `doesn't support .NET Framework 4.7`? ReoGrid should runs on .NET Framework 4.7 without problems.
