### ISSUE TITLE
Reference local variable in another method

### ISSUE THREAD

**Issue by segunodu** [unvell/ReoGrid#28]
Hello Jingwood, I have method_1 with Reogrid control, workbook and worksheets created, I want the code for the calculations in a method_2 so I can call method_2 from method_1. I have tried making the methods public void but it is giving me error. How do you suggest I go about it?
Thank you

**Comment by jingwood** [comment]
What do you want to do? Try post some code and error messages.

**Comment by segunodu** [comment]
This is what I want to do:

        public void workbookCreate()
        {
            var bookS = this.testGridControl;
            var firstSheet = bookS.CreateWorksheet("FIRST SHEET");
            var secondsheet = bookS.CreateWorksheet("SECOND SHEET");
            var thirdSheet = bookS.CreateWorksheet("THIRD SHEET");

            bookS.Worksheets.Insert(0, firstSheet);
            bookS.Worksheets.Insert(1, secondsheet);
            bookS.Worksheets.Insert(2, thirdSheet);

            formular_1();
        }

        public void formular_1()
        {
            var cell_1 = new Cell[] { firstSheet.Cells["E1"], secondsheet.Cells["E1"], thirdSheet.Cells["E1"] };
            var cell_2 = new Cell[] { firstSheet.Cells["E2"], secondsheet.Cells["E2"], thirdSheet.Cells["E2"] };
            var cell_3 = new Cell[] { firstSheet.Cells["E3"], secondsheet.Cells["E3"], thirdSheet.Cells["E3"] };
            var cell_4 = new Cell[] { firstSheet.Cells["E4"], secondsheet.Cells["E4"], thirdSheet.Cells["E4"] };


            foreach (var cell in cell_1)
            {
                cell.Formula = "SUM(B1:D1)";
            }

            foreach (var cell in cell_2)
            {
                cell.Formula = "SUM(B2:D2)";
            }

            foreach (var cell in cell_3)
            {
                cell.Formula = "SUM(B3:D3)";
            }

            foreach (var cell in cell_4)
            {
                cell.Formula = "SUM(B4:D4)";
            }

        }

The code will not compile because firstSheet, secondSheet and thirdSheet in formula_1 method cannot reference firstSheet, secondSheet and thirdSheet in workbookCreate method. This is the error message:

Error	1	The name 'firstSheet' does not exist in the current context	
Error	4	The name 'firstSheet' does not exist in the current context	
Error	7	The name 'firstSheet' does not exist in the current context	
Error	10	The name 'firstSheet' does not exist in the current context	
Error	2	The name 'secondsheet' does not exist in the current context	
Error	5	The name 'secondsheet' does not exist in the current context	
Error	8	The name 'secondsheet' does not exist in the current context	
Error	11	The name 'secondsheet' does not exist in the current context	
Error	3	The name 'thirdSheet' does not exist in the current context	
Error	6	The name 'thirdSheet' does not exist in the current context	
Error	9	The name 'thirdSheet' does not exist in the current context	
Error	12	The name 'thirdSheet' does not exist in the current context

**Comment by segunodu** [comment]
This is what I want to do:

        public void workbookCreate()
        {
            var bookS = this.testGridControl;
            var firstSheet = bookS.CreateWorksheet("FIRST SHEET");
            var secondsheet = bookS.CreateWorksheet("SECOND SHEET");
            var thirdSheet = bookS.CreateWorksheet("THIRD SHEET");

            bookS.Worksheets.Insert(0, firstSheet);
            bookS.Worksheets.Insert(1, secondsheet);
            bookS.Worksheets.Insert(2, thirdSheet);

            formular_1();
        }

        public void formular_1()
        {
            var cell_1 = new Cell[] { firstSheet.Cells["E1"], secondsheet.Cells["E1"], thirdSheet.Cells["E1"] };
            var cell_2 = new Cell[] { firstSheet.Cells["E2"], secondsheet.Cells["E2"], thirdSheet.Cells["E2"] };
            var cell_3 = new Cell[] { firstSheet.Cells["E3"], secondsheet.Cells["E3"], thirdSheet.Cells["E3"] };
            var cell_4 = new Cell[] { firstSheet.Cells["E4"], secondsheet.Cells["E4"], thirdSheet.Cells["E4"] };


            foreach (var cell in cell_1)
            {
                cell.Formula = "SUM(B1:D1)";
            }

            foreach (var cell in cell_2)
            {
                cell.Formula = "SUM(B2:D2)";
            }

            foreach (var cell in cell_3)
            {
                cell.Formula = "SUM(B3:D3)";
            }

            foreach (var cell in cell_4)
            {
                cell.Formula = "SUM(B4:D4)";
            }

        }

The code will not compile because firstSheet, secondSheet and thirdSheet in formula_1 method cannot reference firstSheet, secondSheet and thirdSheet in workbookCreate method. This is the error message:

Error	1	The name 'firstSheet' does not exist in the current context	
Error	4	The name 'firstSheet' does not exist in the current context	
Error	7	The name 'firstSheet' does not exist in the current context	
Error	10	The name 'firstSheet' does not exist in the current context	
Error	2	The name 'secondsheet' does not exist in the current context	
Error	5	The name 'secondsheet' does not exist in the current context	
Error	8	The name 'secondsheet' does not exist in the current context	
Error	11	The name 'secondsheet' does not exist in the current context	
Error	3	The name 'thirdSheet' does not exist in the current context	
Error	6	The name 'thirdSheet' does not exist in the current context	
Error	9	The name 'thirdSheet' does not exist in the current context	
Error	12	The name 'thirdSheet' does not exist in the current context

**Comment by jingwood** [comment]
You should make `firstSheet`, `secondsheet` and `thirdSheet` as class member variable.

**Comment by segunodu** [comment]
Thank you
