### ISSUE TITLE
Does CellBody Class have method such like "refresh()" of winform control?

### ISSUE THREAD

**Issue by sleepingspace** [unvell/ReoGrid#280]
I want to achieve such a function that when the mouse moves inside the cell, the graphics(like rectange or circle drawed in OnPaint event) in the cellbody can follow the mouse. Just like refresh method in WinForm control.

So does Reogrid have?

**Comment by sleepingspace** [comment]
If Reogrid's cell can add custom winform control will be better.

**Comment by sleepingspace** [comment]
I looked at slidecell in the demo code again and found that the "SetCellData" method of worksheet seemed to trigger onPaint events.

**Comment by sleepingspace** [comment]
I got it. I set the return value of the MouseMove event to false (previously mybase. mousemove) and added the SetCellData method.

**Comment by sleepingspace** [comment]
But I still strongly recommend that ReoGrid design an interface for the CellBody class or Cell Class that can add WinForm user-defined controls

**Comment by jingwood** [comment]
Thanks for your suggestion! There are some issues to hold windows form control, like:

1. **Performance issue**. Windows form controls work slower than ReoGrid.
2. **Scale, zoom, scroll, cell freeze**. Windows form controls don't work well with these features.
3. **Print**. Can't print windows form control inside ReoGrid worksheet.

It might be supported in the future with limited usage conditions but I can't ensure it.

**Comment by sleepingspace** [comment]
Thank you
