### ISSUE TITLE
如何在.net4.7上运行该控件

### ISSUE THREAD

**Issue by yujiaocao** [unvell/ReoGrid#281]
如何在.net4.7上运行该控件？
目前在官方网站上下载的控件，只能在.net3.5的运行环境下使用。
是否有考虑何时更新到.net4.7的运行环境的控件？

**Comment by sleepingspace** [comment]
The author is japanese, you‘d better speak in english 哈哈哈，我英语也不好，都是用的百度翻译的哈哈

**Comment by jingwood** [comment]
Please post your issue in English.
