### ISSUE TITLE
ActionPerformed were triggered twice after editing a cell.

### ISSUE THREAD

**Issue by closetao** [unvell/ReoGrid#282]
create a new WPF Project

MainWindow.xaml
```xml
<Window xmlns:reoGrid="clr-namespace:unvell.ReoGrid;assembly=unvell.ReoGrid"
        ...
        >
    <Grid>
        <reoGrid:ReoGridControl Name="ReoGrid"></reoGrid:ReoGridControl>
    </Grid>
</Window>

```
MainWindow.xaml.cs
```csharp
public MainWindow()
{
    InitializeComponent();
    ReoGrid.ActionPerformed += ReoGrid_ActionPerformed;
}

private void ReoGrid_ActionPerformed(object sender, unvell.ReoGrid.Events.WorkbookActionEventArgs e)
{
    Console.WriteLine("ReoGrid_ActionPerformed: " + e.Action.GetType().ToString());
}
```

**Describe the bug**
ReoGrid_ActionPerformed were triggered twice after editing a cell.

**Expected behavior**
ReoGrid_ActionPerformed were triggered once after editing a cell.

**Screenshots**

![image](https://user-images.githubusercontent.com/13362687/66749281-08c68100-eebc-11e9-832f-486358a2aa76.png)

**Comment by jingwood** [comment]
@closetao Thanks!
