### ISSUE TITLE
Date format

### ISSUE THREAD

**Issue by cheasoksereyoudom** [unvell/ReoGrid#283]
```
!!! Reproduce the bug is important !!!
Post your code or upload a project to reproduce the bug
It's difficult to fix the bug without reproduce method
```

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Edition**
Which edition of ReoGrid do you using?
 - Windows Form
 - WPF
 - Android

**Environment (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Language of OS: English

**Additional context**

**Comment by jingwood** [comment]
？？
