### ISSUE TITLE
Data of DropdownListCell can't be saved, Load("xxx.rgf")  can't load the data of DropdownListCell.

### ISSUE THREAD

**Issue by CRREECLEE** [unvell/ReoGrid#286]
1. Data of DropdownListCell can't be saved.
2. Load("xxx.rgf")  can't load the data of DropdownListCell.
3. How to change body-type of cell , like DropdownListCell 2 normal cell.

**Comment by jingwood** [comment]
Loading cell data of drop-down list cell is supported, but loading candidate list of drop-down list cell is not supported by RGF. I recommended you make the candidate list by program rather than loading from external data. Since sometimes the external data should not be trusted.
