### ISSUE TITLE
Support .NET Core 3.0

### ISSUE THREAD

**Issue by Svetomechc** [unvell/ReoGrid#291]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I see this message in VS:
![image](https://user-images.githubusercontent.com/36156020/68586172-1c521100-0495-11ea-8729-3ecd2b88c2c1.png)

**Describe the solution you'd like**
Re-target the app to **netcoreapp3.0**

**Describe alternatives you've considered**
1. Multi-target the app to **netcoreapp3.0**/**net48** (or older versions of .NET Framework)
2. Re-target the app to **netstandard2.1**/**netstandard2.0**

**Additional context**
https://github.com/hvanbakel/CsprojToVs2017
https://github.com/dotnet/try-convert

**Comment by jingwood** [comment]
How to reproduce this problem?

**Comment by Svetomechc** [comment]
@jingwood well, it's not a problem, actually, just an improvement. Your library already works as is in .NET Core 3.0 projects. But the warning above is pretty annoying (:

To reproduce the warning you just need to create a new .NET Core 3.0 windows forms / wpf project, and add your library through nuget.

**Comment by Dunkhan** [comment]
Workaround:
https://stackoverflow.com/questions/45738982/how-to-hide-net-core-compatibility-warnings-when-referencing-net-4-6-nuget-pac

**Comment by jingwood** [comment]
Resolved by #390 and #391
