### ISSUE TITLE
bug  drawing RichText when using ReoGrid2.1.0.0

### ISSUE THREAD

**Issue by qilinfp** [unvell/ReoGrid#297]
when i use reogrid2.1.0.0 to draw RichText  
```
sheet.Cells["B2"].Style.VAlign = ReoGridVerAlign.Middle;
sheet.Cells["B2"].Style.HAlign = ReoGridHorAlign.Center;
```
the style.HAlign can't work, it work like style.VAlign
and the other attribute  of Style.HAlign can't work too.

**Comment by jingwood** [comment]
When using rich text, you should set the paragraph alignment property rather than cell style.

If you still have the problem please reopen this. Thanks!
