### ISSUE TITLE
View_AllowCellTextOverflow does not seem to work

### ISSUE THREAD

**Issue by ziezo** [unvell/ReoGrid#301]
**Describe the bug**
View_AllowCellTextOverflow does not seem to work

**To Reproduce**
```
        private void Form1_Load(object sender, EventArgs e)
        {
            var grid = new unvell.ReoGrid.ReoGridControl()
            {
                Dock = DockStyle.Fill,
            };      
            grid.CurrentWorksheet.DisableSettings(WorksheetSettings.View_AllowCellTextOverflow);
            grid.CurrentWorksheet["A1"] = "asdf asdf asdf asdf asdf asdf asdf asdf";
            this.Controls.Add(grid);  // add to form or panel
        }
```

**Expected behavior**
Text in cell should not overflow

**Screenshots**
![image](https://user-images.githubusercontent.com/36749330/73665004-ae3a7600-46a0-11ea-89e2-09e47233833b.png)

**Edition**
Which edition of ReoGrid do you using?
 - Windows Form (2.1.0.0 from nuget)

**Environment (please complete the following information):**
 - OS: Windows 10
 - Language of OS: English

**Comment by jingwood** [comment]
Hi @ziezo! Fixed, Please try the latest source code.
