### ISSUE TITLE
How to properly update cell with custom object

### ISSUE THREAD

**Issue by LamerDrv** [unvell/ReoGrid#307]
Hi. Thank you very much for your awesome library.
I have question. How to properly update cell value if I have assigned custom data type to cell and then update my custom object?
In my application I have bunch of custom objects:
```
public partial class SchedEvent
{
    public virtual int EventId { get; set; }
    public virtual DateTime EventDate { get; set; }
    public virtual string Caption { get; set; }
    public virtual bool IsCompleted { get; set; }
}
```
and I assign my objects to cells directly:
```
List<SchedEvent> eventsOnGraphic = LoadMyEvents();
.....
sheet.Cells[i, j].Data = eventsOnGraphic[m];
```

I have used IDataFormatter interface for returning string ("Completed"/"Not completed") based on IsCompleted property of my object :
```
class MyReoGridCellFormatter : IDataFormatter
{
  public string FormatCell(Cell cell)
  {
    var ev = cell.Data as SchedEvent;
    if (ev != null)
    { 
       if (ev.IsCompleted)
       { 
          return "Completed";
       }
       else
       {
          return "Not completed";
        }
    }
    else
      return null;
  }
  public bool PerformTestFormat()
  {
    return true;
  }
}
```
   
If I change property IsCompleted of my object assigned to cell.Data what shall I do for update (repaint) cell?
I have tried to call Worksheet.RequestInvalidate(), but it dosn't work.
Is there any public "Update" method or something?

**Comment by jingwood** [comment]
Hi! Currently the simplest method to update the cell content from a custom object is to set the custom object again into the worksheet.

```csharp
myobj.IsCompleted = true;
sheet.Cells[1, 1].Data = myobj;
```

And for the data formatter, I think you can just use `toString` method instead of a customized data formatter. `toString` is more simpler.

```csharp
public partial class SchedEvent
{
  ...
  public override string ToString() => IsCompleted ? "Completed" : "Not completed";
}
```

**Comment by LamerDrv** [comment]
Thank you very much.

P.S: about IDataFormatter vs ToString(). If I understood correctly, in ToString() I can return just string.
But in IDataFormatter.FormatCell(Cell cell) I can make more complicated formatting:
```
public string FormatCell(Cell cell)
{
  var ev = cell.Data as SchedEvent;
  if (ev != null)
  {
    if (ev.IsCompleted)
    {
      cell.Style.BackColor = Color.Green;
      return string.Format(@"В");
    }
    else
    {
      cell.Style.BackColor = Color.Red;
      return string.Format(@"Н");
    }
  }
  else
  {
    return null;
  }
}

```

**Comment by jingwood** [comment]
@LamerDrv Yes, you are correct! Nice work on `IDataFormatter.FormatCell`.
