### ISSUE TITLE
Wpf: set textcolor to red doesn't work! Not Refresh the sheet

### ISSUE THREAD

**Issue by CRREECLEE** [unvell/ReoGrid#316]
In Wpf:
```csharp
sheet.SetRangeStyles("B2:B2", new WorksheetRangeStyle()
{
  Flag = PlainStyleFlag.TextColor,
  TextColor = Color.Red,
});
```
dosen't work.Not Refresh the sheet. 
(If I save the sheet, and then, Load the sheet rfg file, the Color is red!)

But, In Winform:It works well.
A bug?

**Comment by jingwood** [comment]
Fixed, please check from the latest source code.

**Comment by CRREECLEE** [comment]
It works well now! Thanks you so much... ...
