### ISSUE TITLE
WPF. Bug with ViewPort position in the grid with frozen cell

### ISSUE THREAD

**Issue by EgorDudarev** [unvell/ReoGrid#319]
**Describe the bug**
Hi. When grid has frozen rows or frozen columns then after SetColumnsWidth or SetRowsHeight in frozen area other viewports not change StartView property in ViewPort.

This behavior can be seen in demo project.

1. Start "WPFDemo.exe"
2. Select cell A9
3. Select menu item Sheet -> Freeze To Cell
4. Increase 6th row height by 2 times
5. See error (8th row displayed twice)

**Expected behavior**
8th row displayed once

**Edition**
 - WPF

**Screenshot**
![image](https://user-images.githubusercontent.com/62702812/77648862-a1dce600-6f8a-11ea-8e9d-4411add01ae3.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - Language of OS: any

**Comment by jingwood** [comment]
Happening in both Windows Form and WPF. Caused by #315
