### ISSUE TITLE
Copy/Paste on readonly cell will overwrite content

### ISSUE THREAD

**Issue by Xcone** [unvell/ReoGrid#32]
Hi,

Copying one cell, and pasting it on a readonly cell will write the data regardless.

I expect a readonly cell to be really readonly. For such I already provided you with a pull request regarding autofillserial, that also had this problem. And now create this issue reagrding copy/pasting. This copy/pasting logic goes quite a bit deeper in the solution and touches quite a lot of aspects of ReoGrid. So I don't feel confident doing this change without diving a lot deeper into Reogrid. I hope you can help here.

Regards,
Koen

**Comment by jingwood** [comment]
Hi! thanks for the pull request and Issue. Does #33 solve this issue?

**Comment by Xcone** [comment]
It seems the copy action is blocked properly. But I don't see a popup message why not. I took the liberty to look at the change you made, and it seems to suggest a message should be shown to the user.
I'm not sure if my test is proper, though. I hijacked the feature/SetEditableRange demo, and set the cells to readonly instead of making them the only ones you can edit.

However, it is a workable solution for me. The data is readonly cells is preserved, which is what I'm after.

An inconsistancy is now introduced, though. Your fix for copy paste will abort the whole action in case of readonly cells. The pull request I prepared for you that guards readonly cells during autofill serial just ignores the readonly cells, but does provide data to writable cells. I can imagine you'd wish to keep that the same, and abort the AutoFill serial action in case readonly cells are in range as well.

**Comment by jingwood** [comment]
> But I don't see a popup message why not. I took the liberty to look at the change you made, and it seems to suggest a message should be shown to the user.

ReoGrid allows application to decide whether show a dialog to end user. This code makes exception happen:
https://github.com/unvell/ReoGrid/pull/33/files#diff-945770d4e9b0480b548f3d87af699e9eR312

To catch it and show a dialog:

```csharp
workbook.ExceptionHappened += (s, e) =>
{
  if (e.Exception is OperationOnReadonlyCellException)
  {
    MessageBox.Show(this, LangResource.Msg_Operation_Aborted,
      "ReoGrid Editor", MessageBoxButtons.OK, MessageBoxIcon.Stop);
  }
};
```

As you pointed out, the ReoGrid Editor should do this, I have update the pull request #33.
Shall we do this same check in your pull request #31 for the auto filling feature?

**Comment by Xcone** [comment]
That was my intent by mentioning the inconsistency. I updated the pull request to throw an exception when readonly cells are in range, similar to your fix.
