### ISSUE TITLE
NullReferenceException in MeasureCellText

### ISSUE THREAD

**Issue by patchcad** [unvell/ReoGrid#320]
Hello,

I haven't been able to isolate under which conditions this happens, but periodically, when I dispose of a window a ReoGrid control was on, I get a **NullReferenceException** on the **Graphics.cs** file:

`
SizeF size = g.MeasureString(cell.DisplayText, scaledFont, fieldWidth, sf);
`

**g is null**, as are **this.PlatformGraphics** and **this.cachedGraphics**.

drawMode is DrawMode.View

Trace Stack:

`>	unvell.ReoGrid.dll!unvell.ReoGrid.WinForm.GDIRenderer.MeasureCellText(unvell.ReoGrid.Cell cell, unvell.ReoGrid.Rendering.DrawMode drawMode, float scale) Line 889	C#
 	unvell.ReoGrid.dll!unvell.ReoGrid.Worksheet.UpdateCellTextBounds(unvell.ReoGrid.Rendering.IRenderer ig, unvell.ReoGrid.Cell cell, unvell.ReoGrid.Rendering.DrawMode drawMode, float scaleFactor, unvell.ReoGrid.Core.UpdateFontReason reason) Line 912	C#
 	unvell.ReoGrid.dll!unvell.ReoGrid.Worksheet.UpdateCellTextBounds(unvell.ReoGrid.Rendering.IRenderer ig, unvell.ReoGrid.Cell cell, unvell.ReoGrid.Rendering.DrawMode drawMode, unvell.ReoGrid.Core.UpdateFontReason reason) Line 862	C#
 	unvell.ReoGrid.dll!unvell.ReoGrid.Worksheet.UpdateCellRenderFont(unvell.ReoGrid.Rendering.IRenderer ir, unvell.ReoGrid.Cell cell, unvell.ReoGrid.Rendering.DrawMode drawMode, unvell.ReoGrid.Core.UpdateFontReason reason) Line 840	C#
 	unvell.ReoGrid.dll!unvell.ReoGrid.Worksheet.UpdateCellFont(unvell.ReoGrid.Cell cell, unvell.ReoGrid.Core.UpdateFontReason reason) Line 806	C#
 	unvell.ReoGrid.dll!unvell.ReoGrid.Views.NormalViewportController.UpdateNewVisibleRegionTexts.AnonymousMethod__0(int r, int c, unvell.ReoGrid.Cell cell) Line 373	C#
 	unvell.ReoGrid.dll!unvell.ReoGrid.Data.Index4DArray<unvell.ReoGrid.Cell>.Iterate(int row, int col, int rows, int cols, bool ignoreNull, System.Func<int, int, unvell.ReoGrid.Cell, int> iterator) Line 704	C#
 	unvell.ReoGrid.dll!unvell.ReoGrid.Views.NormalViewportController.UpdateNewVisibleRegionTexts(unvell.ReoGrid.Views.GridRegion region, unvell.ReoGrid.Views.GridRegion oldVisibleRegion) Line 362	C#
 	unvell.ReoGrid.dll!unvell.ReoGrid.Views.NormalViewportController.UpdateViewportVisibleRegion(unvell.ReoGrid.Views.Viewport viewport, unvell.ReoGrid.Views.GridRegion range) Line 348	C#
 	unvell.ReoGrid.dll!unvell.ReoGrid.Views.NormalViewportController.UpdateVisibleRegion() Line 307	C#
 	unvell.ReoGrid.dll!unvell.ReoGrid.Views.NormalViewportController.UpdateController() Line 797	C#
 	unvell.ReoGrid.dll!unvell.ReoGrid.Worksheet.UpdateViewportControllBounds() Line 119	C#
 	unvell.ReoGrid.dll!unvell.ReoGrid.ReoGridControl.canvasElements_VisibleChanged(object sender, System.EventArgs e) Line 305	C#
 	[External Code]	
 	unvell.ReoGrid.dll!unvell.ReoGrid.ReoGridControl.OnVisibleChanged(System.EventArgs e) Line 1368	C#
 	[External Code]	
 	unvell.ReoGrid.dll!unvell.ReoGrid.ReoGridControl.WndProc(ref System.Windows.Forms.Message m) Line 1334	C#
 	[External Code]	
 	unvell.ReoGrid.dll!unvell.ReoGrid.ReoGridControl.Dispose(bool disposing) Line 323	C#`

**Comment by jingwood** [comment]
Fixed by #489
