### ISSUE TITLE
wpf: set ControlAppearanceColors.GridBackground don't work

### ISSUE THREAD

**Issue by Yokosama** [unvell/ReoGrid#322]
Set ReoGridControl.ControlStyle's ControlAppearanceColors.GridBackground don't work

**Screenshots**
my code:
![2222](https://user-images.githubusercontent.com/19573211/77882069-cdb1e180-7292-11ea-8baf-266daa589dea.png)

running results:
![111](https://user-images.githubusercontent.com/19573211/77882065-cb4f8780-7292-11ea-9eb6-171a0882b25d.png)

**Edition**
Which edition of ReoGrid do you using?
 - WPF

**Environment (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Language of OS: Chinese

**Comment by jingwood** [comment]
This problem has been fixed and will be available from the next release.
