### ISSUE TITLE
Can the reogrid do this?

### ISSUE THREAD

**Issue by ivi-cc** [unvell/ReoGrid#335]
This is someone else's grid
![1](https://user-images.githubusercontent.com/5524105/82111990-a5ffd580-977b-11ea-863c-692a54fca19c.png)
and this is my grid,I want to be like it. has line and circle.
![2](https://user-images.githubusercontent.com/5524105/82111991-a7c99900-977b-11ea-8a59-479c421ed094.png)

What method should I use? Thanks.

**Comment by waizui** [comment]
not in current version ,but you can modify the source code to add another drawing layer to draw those lines .

**Comment by chencun** [comment]
> not in current version ,but you can modify the source code to add another drawing layer to draw those lines .

oh, it's hard to me.

**Comment by jingwood** [comment]
Hi @ivi-cc, as @waizui said you may have to implement this by your own code since currently we haven't a plan to make it available as a built-in feature. 

I'm going to close this and if you have other questions please feel free to open the new.
