### ISSUE TITLE
Missing unvell.ReoGridEditor.dll in ReoGrid-2.0.0-All-Packages.zip

### ISSUE THREAD

**Issue by RichardHau** [unvell/ReoGrid#34]
Hi, 

Is unvell.ReoGridEditor.dll missed in ReoGrid 2.0? Please check & advise, Thanks

**Comment by jingwood** [comment]
The `unvell.ReoGridEditor.exe` is the DLL in demo folder. If you really need a DLL of editor library rather then EXE you can download the source code and build a DLL manually.

**Comment by RichardHau** [comment]
Hi Jing,

 

From your ReoGrid-2.0.0-All-Packages download, it contains ReoGrid-2.0.0-Demo-Source.zip the source-code for demo program only, there is no source code for the following DLL, unvell.ReoGrid.dll, unvell.ReoGridEditor.dll, unvell.ReoScript.dll & unvell.ReoScript.EditorLib.dll, but these DLL source were available in previous version.

 

Question 1: It is your license policy changed?

Question 2: Can I obtain these DLL’s source code? If these DLL sources require extra license, please inform us the license cost, terms & conditions.

 

Regards,

Richard Hau

**Comment by jingwood** [comment]
All source code of ReoGrid and Editor library can be accessed from here
https://github.com/unvell/ReoGrid
(You may have to use git or GitHub desktop to download it)

License changed to MIT since 2017. There is no extra licenses required. Hope ReoGrid helps you.

**Comment by RichardHau** [comment]
I have downloaded, thanks.
