### ISSUE TITLE
Visual Studio 2019 WinForms System.UnauthorizedAccessException: error while saving as excel

### ISSUE THREAD

**Issue by MIMAXUZ** [unvell/ReoGrid#345]
I am using the latest build of Visual Studio 2019. Today I tried to save the created ** grid ** to excel but it gives the following error.
```
System.UnauthorizedAccessException: 'access to path is denied "E:\VSProjects\GTIvaNSF\GTIvaNSF\bin\Debug".'
```
My code follow as:
```
private void SaveToExcelBtn_Click(object sender, EventArgs e)
        {
            string path = Path.GetDirectoryName(Application.ExecutablePath);
            //var workbook = ReoGridControl.CreateMemoryWorkbook();
            var sav_as = ResultGrid.CurrentWorksheet.Workbook;
            sav_as.Save(path, FileFormat.Excel2007);
        }
```
I tried almost all of the results from Google but there were no results. 
Also i tried **Run As Administrator** and **Permissions ** but no solution yet. How can i fix it?
Such a error would not have happened at all before...

**Comment by jingwood** [comment]
Please post the full stack trace info of the exception. Thanks.

**Comment by MIMAXUZ** [comment]
Thanks @jingwood, I fixed it as following:
```
            string path = @"C:\ExcelFolder\result.xlsx";
            var fileinfo = new FileInfo(path);
             // Try to create the directory.
            DirectoryInfo di = Directory.CreateDirectory(fileinfo.Directory.FullName);
             workbook = ResultGrid.CurrentWorksheet.Workbook;
            workbook.Save(path, FileFormat.Excel2007);
```
To save the file, we need to declare the directory as a *string*. Typically *Path.GetDirectoryName (Application.ExecutablePath)*; can not be used to create a file from it. Because in this view the directory does not have a string view. That's why we need to declare the directory as a string as like:
```
            string path = @"C:\ExcelFolder\result.xlsx";
```
Thank you all!
