### ISSUE TITLE
InvalidOperationException when saving a Memory Workbook

### ISSUE THREAD

**Issue by andreaskarsnas** [unvell/ReoGrid#35]
We currently use ReoGridWPF to export some data to an xlsx-file and not as an actual WPF component. When Saving a MemoryWorkbook from a thread that is not the thread owning the MainWindow, we get an InvalidOperationException that says 'The calling thread cannot access this object because a different thread owns it'. This comes from the fact that during the call to the Save function of the IWorkbook, the following code is executed (in a function called PlatformUtility.GetDPI()):

PresentationSource source = PresentationSource.FromVisual(Application.Current.MainWindow);

Hence, as current thread does not own the MainWindow, the exception is thrown. This behavior does not really make sense for a Memory Workbook as the code using the workbook does not necessarily include a MainWindow. In our case, we can work around this error by calling the Save-functionality a first time from the main tread with a dummy export name in order to get a DPI that is then re-used in the GetDPI-function, avoiding calling the line throwing the exception above. But it doesn't really feel like a nice solution. My belief is that the Memory Workbook should not be dependent on having a MainWindow at all.

**Comment by jingwood** [comment]
> My belief is that the Memory Workbook should not be dependent on having a MainWindow at all.

Agreed. This should be improved. As a solution a dummy window used instead of MainWindow, I have submitted the pull request #36, does it resolve your problem?
 
Debug DLL of WPF edition can be downloaded from:
https://reogrid.net/packages/2.x/2.0.2.0/WPFDebug/

Or you can check out the pull request directly.
