### ISSUE TITLE
export csv for Null Cell

### ISSUE THREAD

**Issue by painezeng** [unvell/ReoGrid#351]
if the cell is null , the csv format is wrong for empty cells.
like double for empty cell.

![image](https://user-images.githubusercontent.com/18071092/86530405-08a75f00-beeb-11ea-84c6-5acd886f09d3.png)

![image](https://user-images.githubusercontent.com/18071092/86530827-b49e7980-beee-11ea-9d65-7e93ee7a87cb.png)

 - Windows Form

 - OS: [ Windows 10]
 - Language of OS: CN

**Comment by tz850** [comment]
yes，it‘s a bug.

```
				for (int r = range.Row; r <= maxRow; r++)
				{
					if (sb.Length > 0)
					{
						sw.WriteLine(sb.ToString());
						sb.Length = 0;
					}

					for (int c = range.Col; c <= maxCol;)
					{
						if (sb.Length > 0)
						{
							sb.Append(',');
						}

						var cell = this.GetCell(r, c);
						if (cell == null || !cell.IsValidCell)
						{
							sb.Append(','); 
							c++;
						}
						else
						{

```

**Comment by jingwood** [comment]
Thanks @painezeng and @tz850, this bug has been fixed now, please check from latest source code.

**Comment by painezeng** [comment]
thanks to so fast close it.
