### ISSUE TITLE
Checkbox CellType in Merged Cells

### ISSUE THREAD

**Issue by mnecc1977** [unvell/ReoGrid#354]
If a CellType is Checkbox and the cell is merged with more rows (for example: A5:A37 is merged), the checkbox only capture mouse events if cell is aligned vertically to top... Looks like the mouse position is constrained only to A5 cell area (in this example), not the entire A5 to A37 area.

**Comment by jingwood** [comment]
I tested the problem you described with both Windows from and WPF edition.
I want to confirm and fix it but I can't find any problems in my environment with the latest code.

```cs
sheet = grid.NewWorksheet();
sheet.MergeRange("A5:A37");
sheet["A5"] = new CheckBoxCell();
```

So this issue will be closed and please let me know if you still have the problem.
Any code or sample project to reproduce the problem will be helpful.
