### ISSUE TITLE
Fill handle event

### ISSUE THREAD

**Issue by CmeFrog** [unvell/ReoGrid#356]
Sorry to bother you again.  I have a grid inside of a project management app.  The columns are datetimes and the rows are people.  The task ID is displayed in the cells.  A task may take one column (30 minutes) or more than one.  If more than one column is needed then they are merged.  I disabled the fill handle as per your instructions so no new data could be added and all was working well.  I now have a request to add the capability to increase the time allocated for a task.  If a task is to be lengthened then the user should grab the fill handle and drag it to the right.  When the fill handle is dropped I would like to be able to add the additional new cell(s) to the existing task cell(s).  If the task had been represented in a single column then merge old cell with new cell(s).  If the task was already occupying more than one column then new cell(s) should be added to existing merged ones.  So I need some kind of event when the fill handle is dropped.  I have looked for an event that would help me accomplish this but can't find one.  I looked for some kind of fill handle event and also inside of CellMouseDown/Up to see if there is a way to tell whether or not the fill handle is active. If there is not a way to monitor the fill handle please create one.  Thanks

**Comment by jingwood** [comment]
Thanks for your information. Can you please explain more about what is the problem? 
You can try the issue template to describe your problem, sorry but I have to close this.
