### ISSUE TITLE
Tags not reset

### ISSUE THREAD

**Issue by CmeFrog** [unvell/ReoGrid#357]
If you move either a single cell or a merged range the From cell tags are not set back to null.  They  remain the unchanged.  The To cell tags all contain the correct copies of the From tags so no problem there.  The From cell Data property does seem to be reset to null after the move so that seems to work as expected.  The reason I am checking is to see if a row is empty.  My check has to account for the scenario where a cell or merged range have been moved to another row.  I was checking the Tag property since when I put a value in a cell I also set that cell's tag with the record key from my database table.  Now I will use the Data property so this not a problem for me.  However it is obvious to me that you are committed to whatever you decide ReoGrid will do, it will do well.  So I thought you would like to know.

```csharp
unvell.ReoGrid.Worksheet sheet = Grid1.CurrentWorksheet;
sheet.SetSettings(WorksheetSettings.Edit_DragSelectionToMoveCells, true);
sheet.AfterRangeMove += Sheet_AfterRangeMove;

private void Sheet_AfterRangeMove(object sender, CopyOrMoveRangeEventArgs e)
{
        unvell.ReoGrid.Cell currCell = Grid1.CurrentWorksheet.Cells[e.FromRange.Row, e.FromRange.Col];
        MessageBox.Show($"From tag = {currCell.Tag}");
}
```

Thanks for your good work.

**Comment by jingwood** [comment]
Thanks for your information. Can you please explain more about what is the problem?
