### ISSUE TITLE
How to change column header styles? Such as displays item and unit with two lines.

### ISSUE THREAD

**Issue by gqzxm** [unvell/ReoGrid#358]
as attachment picture.

![image](https://user-images.githubusercontent.com/25242417/87871218-28f21600-c9e1-11ea-9a90-ec3b84defdca.png)

**Comment by transistor1** [comment]
@gqzxm Did you ever figure out how to do this?  

@jingwood Is this possible to do with a custom header?

**Comment by jingwood** [comment]
@transistor1 @gqzxm Currently only the `HeaderBody` can be used to extend the header appearance, but text line-wrap, multiple line text and customized height of column header are not supported. I will try to make the custom header.

**Comment by gqzxm** [comment]
add a public function in headers.cs as following:
		public void SetColHeaderHeight(ushort nHeight)
		{
			if (nHeight <= 1) nHeight = 1;
			if (nHeight >= 10) nHeight = 10;

			colHeaderHeight = (ushort)(nHeight*18);
		}
It works well.
