### ISSUE TITLE
Count of selected items

### ISSUE THREAD

**Issue by shadrackkibet** [unvell/ReoGrid#360]
How do you count the number of selected items via a checkbox in ReoGrid? I tried `grdFactorData.CurrentWorksheet.SelectionRange.Rows` but this returns the count of highlighted rows.

![image](https://user-images.githubusercontent.com/26301973/89707000-3f9de400-d973-11ea-911c-89ce5bea0de7.png)

**Comment by jingwood** [comment]
You may have to use your own logic to count the selected items like this:

```csharp
int count = 0;
for (int r = 0; r < 10; r++){
  if (sheet[r, 4] is bool selected) count++;
}
```

Thanks for post.
