### ISSUE TITLE
How to change the font size for header?

### ISSUE THREAD

**Issue by painezeng** [unvell/ReoGrid#363]
I can't find any option to set the font size for coloum header. 
 it is too small .  I am not sure i missing something?
![image](https://user-images.githubusercontent.com/18071092/91467455-2c6f9b80-e8c3-11ea-8ddb-3a0308506780.png)

**Comment by liusaiweng** [comment]
同问 我的解决办法 不用列头 自己起一行当列头

**Comment by jingwood** [comment]
Current version doesn't support to change font of header text. Thanks.
