### ISSUE TITLE
System.ThrowHelper.ThrowArgumentOutOfRangeException() c__DisplayClass17_0

### ISSUE THREAD

**Issue by liusaiweng** [unvell/ReoGrid#374]
i have this bug for a long time,and unable to find why
在 System.ThrowHelper.ThrowArgumentOutOfRangeException()
在 unvell.ReoGrid.Views.CellsViewport.<>c__DisplayClass17_0.b__0(Int32 i)
在 unvell.ReoGrid.Data.ArrayHelper.QuickFind(Int32 split, Int32 start, Int32 end, Func`2 compare)
在 unvell.ReoGrid.Views.CellsViewport.GetRowByPoint(IViewport view, Single y)
在 unvell.ReoGrid.Views.CellsViewport.GetPosByPoint(IViewport view, Point p)
在 unvell.ReoGrid.Views.CellsViewport.OnMouseMove(Point location, MouseButtons buttons)
在 unvell.ReoGrid.Views.ViewportController.OnMouseMove(Point location, MouseButtons buttons)
在 unvell.ReoGrid.ReoGridControl.OnWorksheetMouseMove(PointF location, MouseButtons buttons)
在 unvell.ReoGrid.ReoGridControl.OnMouseMove(MouseEventArgs e)
在 System.Windows.Forms.Control.WmMouseMove(Message& m)
在 System.Windows.Forms.Control.WndProc(Message& m)
在 unvell.ReoGrid.ReoGridControl.WndProc(Message& m)
在 System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
在 System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by jingwood** [comment]
Please provide the sample code or data to reproduce the problem you described. Thanks!
