### ISSUE TITLE
Value of an empty cell

### ISSUE THREAD

**Issue by KDA54** [unvell/ReoGrid#378]
Hi,

I have read in an Excel workbook that has some complicated formulas. The functions used by these fourmulas are all supported by Reogrid - LEN, TRIM, LEFT, etc.

But the formulas are failing, and the reason seems to be when an empty cell is examined. The Excel formula is like:
```
    =IF(W3="", "<empty>", "<value>")
```
but if `W3` is indeed empty the formula evaluation is still giving "<value>", and I think the value is a nueric zero.

I tried changing the test to be `LEN(W3)=0`, but that did not change the result.

Is there a configuration option I need to set somewhere, or is this an inherent limitation of fault in the processing?

Thanks for any help

Kevin

**Comment by jingwood** [comment]
Do you want to check whether a cell has value or not?

**Comment by KDA54** [comment]
Hi, thanks for getting back to me on this.

 

Rereading my original message it now seems to be less clear that it could be.

 

What I was looking for, was for the spreadsheet functions TRIM, LEFT, RIGHT, LEN (and maybe other similar function too) to treat a non-existent (null) cell in a spreadsheet as being a zero-length string.

 

I created a workaround by modifying my formulas to use ISBLANK before applying LEN, TRIM, LEFT, etc, and created a custom implementation for ISBLANK.

    static object func_ISBLANK(Cell celCurr, params object[] args) {

        bool blnNullArg = (args[0] == null);

        bool blnIsBlank = blnNullArg || (args[0].ToString() == "");

         return (bool)blnIsBlank;

    }

 

It works, but makes some complex spreadsheet formulas very complicated indeed.

At this point, I do not need to know if the cell is null or not – just that it is a zero-length string.

 

Thanks for your help.

 

Kevin

**Comment by jingwood** [comment]
Your workaround solution looks good. 

How to evaluate a cell that has a valid value, check null? or check empty string, I think that is more decided by application. 
Excel handles the cell's value as a string, but ReoGrid allows it can be anything.

I'm considering adding a built-in function like 'ISNULL' or 'ISBLANK' to help to check the data is null or not, but I don't sure other users will think it helps.

I'm going to close this, if you have other questions or problems, please feel free to open any new issues, thanks!
