### ISSUE TITLE
FreezePanes

### ISSUE THREAD

**Issue by Furgia** [unvell/ReoGrid#38]
Reogrid support FreezePanes ?
If yes how can I do to use this function ?
Many thanks

**Comment by jingwood** [comment]
https://reogrid.net/document/freeze/

**Comment by Furgia** [comment]
Opps, thank-you.
I did not see the link on the documentation page.
Is there a pdf document with all the features or is it possible to consult the documentation online only?

**Comment by Furgia** [comment]
Opps, thank-you.
 I did not see the link on the documentation page.
 Is there a pdf document with all the features or is it possible to consult the documentation online only?

**Comment by Furgia** [comment]
Opps, thank-you.
 I did not see the link on the documentation page.
 Is there a pdf document with all the features or is it possible to consult the documentation online only?

**Comment by alexey77777** [comment]
> Is there a pdf document with all the features
Only in russian
https://reogrid.net/ru/document/

**Comment by jingwood** [comment]
@Furgia There is no English version PDF document for all features. You can refer to this index page or use 'Search' at right side: https://reogrid.net/document/
