### ISSUE TITLE
Requesting WPF MVVM example

### ISSUE THREAD

**Issue by animechitransh** [unvell/ReoGrid#382]
Could you please provide a demo application with WPF MVVM. I have used the winform Reogrid and its good. I cannot figure out how to use MVVM pattern with WPF version as there are no dependency properties. I'll be happy to contribute but lack technical expertise.

Thanks

**Comment by jingwood** [comment]
Maybe you can submit an issue to the MVVM team?
https://github.com/IUpdatable/ReoGrid.Mvvm

**Comment by animechitransh** [comment]
Thanks, will post request over there

**Comment by MichalKurzewski** [comment]
have you seen this example?
https://github.com/IUpdatable/ReoGrid.Mvvm/tree/master/ReoGrid.Mvvm.Demo
i think its quite good

**Comment by jingwood** [comment]
Seems has been resolved, so I'm going to close this.
