### ISSUE TITLE
LoadCSV fails used with MemoryWorkbook

### ISSUE THREAD

**Issue by KeiBontakun** [unvell/ReoGrid#383]
**Describe the bug**
Used with MemoryWorkbook LoadCSV throws System.NullReferenceException.
CSV.cs Line 126 has following code and controlAdapter is null.
```
this.controlAdapter.ChangeCursor(CursorStyle.Busy);
```

**To Reproduce**
```
var grid = ReoGridControl.CreateMemoryWorkbook();
var sheet1 = grid.Worksheets[0];
sheet1.LoadCSV(file,Encoding.ASCII);
```
**Expected behavior**
LoadCSV succeeds like Load() Method.

**Edition**
Which edition of ReoGrid do you using?
 - Windows Form
 - ReoGrid 2.1.0.0

**Environment (please complete the following information):**
 - OS: Windows 10
 - Language of OS: English

**Additional context**

**Comment by jingwood** [comment]
Thanks! This is should be fixed.

**Comment by KeiBontakun** [comment]
Thanks, great job!
