### ISSUE TITLE
unvell.ReoGrid.Worksheet.cols' n'est pas accessible dans ce contexte, car il est 'Friend

### ISSUE THREAD

**Issue by touf26** [unvell/ReoGrid#39]
Hello,
I have this message (see in issue title) when i try to change columns numbers
Thanks
`        Dim sheeet As unvell.ReoGrid.Worksheet
        sheeet = ReoGridControl1.CurrentWorksheet
        sheeet.Name = "eee"
        sheeet.Rows = 360
        sheeet.cols = 5
`

**Comment by XLCYun** [comment]
Why you posted a French title... It prompted you unvell.ReoGrid.Worksheet.cols cannot be accessed. 
I think this is not a bug of ReoGrid.
If what you want to do is to set the number of column and row to 360 and 5. Try this:
sheeet.SetRows = 360
sheeet.SetCols = 5

**Comment by alexey77777** [comment]
XLCYun, touf26 use french version of Visual Studio.

**Comment by jingwood** [comment]
Maybe you have to use `Cols` not `cols`.

**Comment by touf26** [comment]
Thanks, setCols works
