### ISSUE TITLE
DemoWPF not working

### ISSUE THREAD

**Issue by yorkolee** [unvell/ReoGrid#4]
DemoWPF not working.  In MainWindow.xaml.cs, InitializeComponent() not found, all 'grid'  not found.

**Comment by jingwood** [comment]
Please post some your code.

**Comment by yorkolee** [comment]
Fixed it.  compiled with .net4.5, reference system.dll,presentationframework.dll,windowsbase.dll and presentationcore.dll, It is working. Thinks.
   By the way, I want a simple grid, Virtual grid can Binding DataTable, List and so on.  What should I do, please give me some good idea.

**Comment by jingwood** [comment]
There is many demo programs in the demo project of source code, or you can download the demo binary from: https://reogrid.net/download

Post a new issue if you have other questions. thanks.
