### ISSUE TITLE
Cell size not right on high DPI device

### ISSUE THREAD

**Issue by xuqiang1015** [unvell/ReoGrid#446]
ReoGrid is great Control, thanks to everybody who works on it!

Now I tried to use ReoGrid(WinForm version) in my MFC program.

My screen DPI is 200%,  cell height is 20 by default, so cell height should be 40 pixcel.

It works fine when I use ReoGrid in winform.

But when I intergate ReoGrid into MFC, cell height turns to be 20 pixcel.

I didn't find the right solution for it.

Anyone konw how to solve it ? Thanks for you help!

My test code is [here](https://github.com/xuqiang1015/WinformHostTest).

## Which edition of ReoGrid is targeted
- Windows Form

**Comment by xuqiang1015** [comment]
I found the reason. ReoGrid does not surpport DPI Aware yet.

I've modified my test code, make the Winform project DPI Aware. Now cells in WinForm project is not right too.

When project is DPI Unaware, cell and font have been scaled by system, so the size is right, but turns into blurry.

These are images to compare under DPI Aware and DPI Unaware mod:

DPI Aware:

![DPI 200 aware](https://user-images.githubusercontent.com/2232517/144012634-c0d7af69-1385-46f4-953b-37b3785c67c1.png)

DPI Unaware:

![DPI 200 Unaware](https://user-images.githubusercontent.com/2232517/144012672-3139ad96-741e-4097-b2e1-599635e803fd.png)

Origin Images are here :
[DPI Aware](https://github.com/xuqiang1015/WinformHostTest/blob/main/img/DPI%20200%20aware.png)
[DPI Unaware](https://github.com/xuqiang1015/WinformHostTest/blob/main/img/DPI%20200%20Unaware.png)

**Comment by xuqiang1015** [comment]
fixed in [pull request](https://github.com/unvell/ReoGrid/pull/448)

**Comment by jingwood** [comment]
Thank you very much!
