### ISSUE TITLE
Is there anyone help translating the Document to Chinese? 

### ISSUE THREAD

**Issue by XLCYun** [unvell/ReoGrid#45]
Hi, I couldn't find a contact in the website, So I post a "issue" in here.
ReoGrid is awesome, but I find out there is no Chinese document in the website(only Japanese, Russian), I wonder is there anyone help translating the Chinese version of the document? 
If there isn't, may I help translating? 
I had help translating some articles for other translting project, and I hope ReoGrid will be more popular in China, if we have a Chinese version. 
Thanks.

**Comment by alexey77777** [comment]
Hi.
It is necessary to wait for the answer of the author of the project.

But usually everything happens like this: you take the English version of the documentation and:
1) you simply translate the English version into your language;
2) you create your version of the documentation.
For example: the Russian version of the documentation is made as one document in HTML and PDF formats

**Comment by XLCYun** [comment]
Hi, @alexey77777 ,thanks for your reply. Yes, it is necessary to wait for the answer from the author, because I don't wanna translate it again if someone is translating already. And I am not sure what you said "used strategy "2" means, could you be more specific?

**Comment by alexey77777** [comment]
> And I am not sure what you said "used strategy "2" means, could you be more specific?
The English version of the documentation contains many separate pages. 1 page = 1 function.
This is convenient for translation, but this option is difficult to use autonomously (without access to the site).

Therefore, the author of the Russian version of the documentation, with the permission of the author of the project, made his draft of documentation, which consists of three parts:
1) a project in Visual Studio with sample code on VB.Net;
2) a project in Visual Studio with examples of code in C #;
3) a short tutorial in HTML format.

As a result of combining these parts, we get a document in the form of a single HTML page, which is also exported to PDF.

Much depends on how it will be more convenient to update the document when the ReoGrid functions are updated.

All the details of the translation must be agreed with the author of the project. He is a good person, so it's easy to choose the right strategy with him.

**Comment by XLCYun** [comment]
oh, i didn't know this kind of procedure before, is there something I can read about it, or what key words should I Google?

**Comment by alexey77777** [comment]
Much depends on you, if you would like to translate the scheme 1 function = 1 page (just translate the English version 1:1, that is, replace the English text with information in your language), use this method.

> I can read about it, or what key words should I Google?

Regular Expressions, MSDN,...

**Comment by jingwood** [comment]
Hi @XLCYun

Thanks for your help! It will be great if you can provide either a combined PDF or multiple HTML file. We will upload your document to ReoGrid homepage.

**Comment by XLCYun** [comment]
Thanks. @alexey77777 @jingwood. I think I will go the HTML way.

**Comment by XLCYun** [comment]
@jingwood some pages of the documentation cannot be found in reogrid.net. such as 
http://reogrid.net/document/freeze/
http://reogrid.net/document/border/
http://reogrid.net/document/group-and-outline/

**Comment by alexey77777** [comment]
@XLCYun, use https-version of links
https://reogrid.net/document/freeze/
https://reogrid.net/document/border/
https://reogrid.net/document/group-and-outline/

**Comment by XLCYun** [comment]
@alexey77777 thanks. It works now. Some links in `Documentation` start with "https", some aren't.

**Comment by alexey77777** [comment]
Thanks @XLCYun

> Some links in Documentation start with "https", some aren't.

I think it will be interesting for @jingwood

**Comment by jingwood** [comment]
Thanks @XLCYun and @alexey77777.

`http` redirecting to `https` now fixed.

**Comment by XLCYun** [comment]
Hi, sorry it took so long, have been crazy busy these several months. I translated the documentation into Chinese, but written in Markdown format, I can convert these files to multiple HTML files, and combine it together into one HTML after that, which one would be preferred?

**Comment by alexey77777** [comment]
Hi XLCYun,
Thank you for your work. Let's wait for a response from jingwood.

**Comment by jingwood** [comment]
@XLCYun Thanks. It would be helpful if you provide the simple or multiple html files. We will upload it to the homepage of ReoGrid.

**Comment by XLCYun** [comment]
@jingwood How should I sent those files to you? Push to this repo, or e-mail?

**Comment by jingwood** [comment]
@XLCYun Can you please send the files to info at reogrid.net, including any future updates. Thanks.

**Comment by XLCYun** [comment]
Why I couldn't find any contact information at reogrid.net ??

**Comment by jingwood** [comment]
Please send mail to info@reogrid.net directly.
