### ISSUE TITLE
Unmerge don't work

### ISSUE THREAD

**Issue by seghier** [unvell/ReoGrid#458]
Hi
I create a windows form and use merge cells , this work fine but unmerge the range don't work
This work fine in the demo editor but not in winform

**Comment by jingwood** [comment]
Please post your code or more details to get helps.

**Comment by seghier** [comment]
Hi [jingwood](https://github.com/jingwood) 
I solve the problem , before i used an example from the website which work only with merge but than i use:
```
position = unvell.ReoGrid.RangePosition()
self.sheet.UnmergeRange(position)
```
And hat's work fine
