### ISSUE TITLE
Hover Hightlight : how

### ISSUE THREAD

**Issue by seghier** [unvell/ReoGrid#459]
Hi
How to create this effect like in demo file?
Hover Hightlight

![image](https://user-images.githubusercontent.com/6026588/157628057-7ce98b71-e559-4e32-82b0-1f4c6408cd7f.png)

**Comment by seghier** [comment]
I find it thanks

**Comment by jingwood** [comment]
Good to hear that. You can find more example code from the source code of demo project. I'm going to close this.
