### ISSUE TITLE
Rank function

### ISSUE THREAD

**Issue by segunodu** [unvell/ReoGrid#46]
Hello Jing, I am trying to implement Excel RANK function using Customize function. 

Code:

```csharp
public static int Rank<T>(T value, IEnumerable<T> data)
{
  return data.OrderByDescending(x => x).ToList().IndexOf(value) + 1;
}
```

Usage:

```csharp
int[] data = new[] { 3, 2, 2, 3, 4 };
int rank = Rank(3, data); // returns 2
```

How do I implement it in Customize function.
Thank you.

**Comment by jingwood** [comment]
Please refer to https://reogrid.net/document/customize-function/

```csharp
unvell.ReoGrid.Formula.FormulaExtension.CustomFunctions["RANK"] = (cell, args) =>
  {
    // sample code

    if (args.Length == 0)
    {
      // this function needs at least one argument
      return null;
    }

    return Convert.ToString(args[0]).ToUpper();
  };
```

Also will be great if you make the function as a standard built-in function of ReoGrid by pushing your change to this repository.

**Comment by segunodu** [comment]
Thank you very much.

**Comment by segunodu** [comment]
Hello Jing, I tried to use RANK in the customize function but I am not getting the desired result

            FormulaExtension.CustomFunctions["RANK"] = (cell, args) =>
                {
                    return Rank(cell, args);
                };

How do I get the data in the reference cell and rank it in the reference range?

**Comment by segunodu** [comment]
I have tried this 

            FormulaExtension.CustomFunctions["RANK"] = (cell, args) =>
                {
                    if(args.Length < 1 || !(args[0] is RangePosition))
                    {
                        return null;
                    }

                    RangePosition range = (RangePosition)args[0];

                    cell.Worksheet.IterateCells(range, (r, c, inCell) =>
                        {
                            double value;

                            CellUtility.TryGetNumberData(inCell.Data, out value);


                        });


                };

But I don't know where to go from there
Thank you

**Comment by jingwood** [comment]
@segunodu Did you solve this?

**Comment by segunodu** [comment]
Hello Jingwood, sorry I have not responded since. I have solved the Rank function issue using a Rank method and creating Customize Rank function.

The method:

		public static double Rank<T>(T value, IEnumerable<T> data)
		{
			return data.OrderByDescending(x => x).ToList().IndexOf(value) + 1;
		}


And the Customize function:

			FormulaExtension.CustomFunctions["RANK"] = (cell, args) =>
			{
				if (args.Length < 1 || !(args[0] is CellPosition || args[1] is RangePosition))
				{
					return null;
				}
				double cellVal = (double)args[0];
				RangePosition rangePos = (RangePosition)args[1];
				List <double> rangeNums = new List<double>();

				cell.Worksheet.IterateCells(rangePos, (r, c, inCell) =>
				{
					double rangeVal;
					
					if (CellUtility.TryGetNumberData(inCell.Data, out rangeVal))
					{
						rangeNums.Add(rangeVal);
					}
					return true;
				});
				double[] rangeArray = rangeNums.ToArray();
				double numPos = Rank(cellVal, rangeArray);
				return numPos;
			};

Thank you very much. I hope this method will be easier to add into the next Reogrid release. If you need help creating other Customize functions, let me know.

Thank you.
