### ISSUE TITLE
Importing currency value under 'English (United Kingdom' locale fails to restore currency and decimal places

### ISSUE THREAD

**Issue by abstractspoon** [unvell/ReoGrid#466]
1. Change system locale to 'English (United Kingdom)'

![image](https://user-images.githubusercontent.com/12944354/168465077-98285214-8a62-4976-987e-e90fb30dc28b.png)

2. Load the attached native Excel file into Winforms Editor
 
![image](https://user-images.githubusercontent.com/12944354/168465187-baeb2284-34e7-4802-808b-728b75b68485.png)

3. ReoGrid loses the currency symbol and 'Currency' type

![image](https://user-images.githubusercontent.com/12944354/168465216-b656ae7b-d632-4e8e-af60-d812ca6a2626.png)
 

[currency.xlsx](https://github.com/unvell/ReoGrid/files/8694590/currency.xlsx)

**Comment by abstractspoon** [comment]
As another example, if you change the locale to 'French (France)' and import the attached native Excel document, you lose both the Currency type and the number of decimals.

Note: This requires [this pull request](https://github.com/unvell/ReoGrid/pull/462) else the number format is also lost.

[french.xlsx](https://github.com/unvell/ReoGrid/files/8694608/french.xlsx)

**Comment by jingwood** [comment]
@abstractspoon Thank you very much! Can we close this since the pull request has been merged?

**Comment by abstractspoon** [comment]
Certainly
