### ISSUE TITLE
help with padding for text

### ISSUE THREAD

**Issue by ObfuscationEqualsTrue** [unvell/ReoGrid#467]
hello, i'm sorry if this is the wrong place to ask for advice.
i have been trying to get a little bit of space in between the edges of the cells and the text, can you recommend a way of doing that?
so far i've tried:
- padding (which affects the drop down box but not the text), i've read this only works on the cell body
- indent (only affects the left of the text)
- ReoGridHorAlign (again just one side)
- overriding OnPaint and calling dc.DrawCellText (i thought it would put the text in the cell body, but maybe i'm not doing it right)

**Comment by jingwood** [comment]
There is a sample that creates a customized cell body with padding value calculation.
You may check if it matches your requirements, but still some issues there, such as

 - It doesn't work with automatic cell text adjustment, if the user double clicks on the column, the width of the column will not fit this cell
 - You have to set this cell body to all cells that use padding, there is might a performance problem
 - You might have to handle the cell's styles manually

The cell body
```cs
class CellWithPaddingBody : CellBody
{
	public override void OnPaint(CellDrawingContext dc)
	{
		var cell = this.Cell;

		// calc the target bounds with padding
		var bounds = this.Bounds;
		bounds.X += 10;         // left padding
		bounds.Width -= 10;     // right padding

		// draw cell background
		dc.DrawCellBackground();

		// draw cell text
		dc.Graphics.DrawText(cell.DisplayText, "Arial", 9, SolidColor.Black, 
			bounds, ReoGridHorAlign.Left, ReoGridVerAlign.Middle);
	}
}
```

Code to use the cell body
```cs
var sheet = this.grid.CurrentWorksheet;

var cell = sheet.Cells["C3"];
cell.Body = new CellWithPaddingBody();

cell.Data = "Hello World";
```

You can handle the cell's styles by using `this.Cell.Style` property in cell body.

**Comment by ObfuscationEqualsTrue** [comment]
wow thanks for the quick reply :) i'll try this out

**Comment by ObfuscationEqualsTrue** [comment]
yes, i'm seeing some good results with your code!
thank you sir
