### ISSUE TITLE
Sorting ranges

### ISSUE THREAD

**Issue by segunodu** [unvell/ReoGrid#47]
Hello Jing, I have a range

var firstRange = sheet1.Ranges["A5:A24"];

and I want to sort in only firstRange, how can I go about it?

Thank you.

**Comment by jingwood** [comment]
The `worksheet.SortColumn` function accepts an argument called `applyRange`, you can pass a range argument that you want to sort, the range you passed will only be changed.

```csharp
public RangePosition SortColumn(int columnIndex, RangePosition applyRange,
	SortOrder order = SortOrder.Ascending,
	CellElementFlag moveElementFlag = CellElementFlag.Data,
	Func<int, int, object, object, int> cellDataComparer = null)
```

**Comment by segunodu** [comment]
Thank you very much
