### ISSUE TITLE
Wrong string concatenation formula behavior

### ISSUE THREAD

**Issue by ycherkes** [unvell/ReoGrid#473]
## Description
ReoGrid adds a wrong number of quotes when calculating the formula with string concatenation.

## To Reproduce

1. ReoGrid Demo 3.0.0 Go to 'File -> New Editor'
2. Type any text, for example: **first** in a cell A1
3. Type a formula `="var " &A1 & "Member=""" &A1 & "Value"";"` in a cell B1
4. Copy the result of the formula to notepad. You've got a **var firstMember=""firstValue"";**
5. The same manipulations in MS Excel give **var firstMember="firstValue";**

## Screenshots
![image](https://user-images.githubusercontent.com/13467759/195054763-6359b269-9c0e-495a-a49b-5f003f7f25e2.png)
![image](https://user-images.githubusercontent.com/13467759/195055084-5988b359-1a54-45cc-ba93-56396f785769.png)
![image](https://user-images.githubusercontent.com/13467759/195055384-3e66633d-0ee1-4313-bbc5-a263dfa72a4e.png)

## Edition
 - Windows Form from the ReoGrid Demo 3.0.0

## Environment
 - OS: Windows 10
 - Language of OS: English

Test workbook for Excel<->ReoGrid behavior comparison:
[TestCodeGeneration.xlsx](https://github.com/unvell/ReoGrid/files/9786836/TestCodeGeneration.xlsx)

**Comment by ycherkes** [comment]
[PR!474](https://github.com/unvell/ReoGrid/pull/474) should fix this issue.

**Comment by jingwood** [comment]
@ycherkes Thanks very much!
