### ISSUE TITLE
Failed to load xlsx?

### ISSUE THREAD

**Issue by er-fie** [unvell/ReoGrid#476]
## Description
My excel is version 2013. When loading the xlsx file, Ionic.Zip appears ZipException:“Cannot read that as a ZipFile”

## Screenshots
![image](https://user-images.githubusercontent.com/74161865/197425778-82a12fdc-c094-49ce-97a3-cdcae30e3c86.png)

## Edition
ReoGrid 3.0.0
 - Windows Form(.NET)

## Environment
 - OS: [e.g. Windows 11]

**Comment by jingwood** [comment]
Can you open the file with Excel without errors? Or have you tried to use a zip tool like 7z to open the file directly.

**Comment by jingwood** [comment]
Close this seems it is not a problem from ReoGrid, if you still have problem please open a new.
