### ISSUE TITLE
CS1061	'ReoGridControl' does not contain a definition for 'RunScript'

### ISSUE THREAD

**Issue by waconline** [unvell/ReoGrid#48]
> CS1061	'ReoGridControl' does not contain a definition for 'RunScript' and no extension method 'RunScript' accepting a first argument of type 'ReoGridControl' could be found (are you missing a using directive or an assembly reference?)	Demo	3	K:\ReoGrid-master\Demo\CellAndRange\MergeCellsDemo.cs

Why it show 32 errors like above when i build in release mode, but no error in debug mode?

**Comment by jingwood** [comment]
You must run with `Extension` configuration. `Release` configuration does not contain extension features like script execution.

**Comment by waconline** [comment]
thanks a lot
