### ISSUE TITLE
Not able to read excel cell data

### ISSUE THREAD

**Issue by ishangandhi1** [unvell/ReoGrid#5]
Hi,

I came across this issue when I was trying to Load an excel file exported from SSRS. The issue in question was because the the Cell class does not support the structure that my file has. The structure is as follows.

<c s="4" t="inlineStr" r="Z5">
        <is>
          <t xml:space="preserve">Exchange</t>
        </is>
</c>

So the ElementText value is always null and nothing comes up on the UI.

**Comment by jingwood** [comment]
Hi, can you upload an Excel sample file that causes the problem happen?

**Comment by ishangandhi1** [comment]
Hi Jing,

I have also raised the issue on github.com and also have provided a sample
of why the data was not visible. I cloned the source and made some changes
to make it work.

**Comment by jingwood** [comment]
Thanks. Can you share and submit your changes as a pull-req?
