### ISSUE TITLE
Cell that hold Custom Data Type

### ISSUE THREAD

**Issue by acanus** [unvell/ReoGrid#50]
Hi,
I'm new to ReoGrid. I want to know if Cell can store custom Data Type  because I see that all the data is convert into string?
Forexample, I have a class call "ImageData" and I want a cell to store this data, then when I pass that Cell to another function, I can access ImageData (not the string value).

Update: I can make the cell to store a custom Data Type now by modified the source code. I create a new `FormulaValueType` named Object then in the `CreateFormulaValue(object obj)` method, instead of convert object to string, I return a new `FormulaValue` with `FormulaValueType.Object` and the value  = object.
Then finally I can use the Cell data (not the string) when using `CustomFunctions`.
Thanks

**Comment by jingwood** [comment]
Congratulation you solved it by yourself. If there is an API/Interface that allows user to save and load custom data when use RGF format would be better to me. So this is planed to be implemented.

**Comment by jingwood** [comment]
@acanus Maybe you can provide a pull request of your change about the formula custom data type. It would be great because your change will also available for other many users.
