### ISSUE TITLE
How to display full text beyond cell limits?

### ISSUE THREAD

**Issue by lotuslakestudio** [unvell/ReoGrid#502]
I'm using this software to creat a .xlsx file like this
![2](https://github.com/unvell/ReoGrid/assets/138570492/16d6d501-bfaf-419f-b16d-48e15470dcdd)
Yet the production of this software  is this
![1](https://github.com/unvell/ReoGrid/assets/138570492/59f9581b-8013-4b77-a093-241e18e465fd)

So, how to get the right format as shown in the first picture?
Thanks in advance.

**Comment by jingwood** [comment]
You have to enable the settings:

```cs
Worksheet.EnableSettings(WorksheetSettings.View_AllowCellTextOverflow);
```

And avoid to set cell background color.

**Comment by lotuslakestudio** [comment]
It seems the above code isn't working. The texts are still being trimmed at the cell border.
I'm using Win10, Visual studio 2022 community, .net framework 4.8.

**Comment by lotuslakestudio** [comment]
I found the problem. This bug occurs because I intorduced another excel program to generate .xlsx files, which named "closedxml". When I fill the cells by code, the format is correct.

**Comment by jingwood** [comment]
So if the problem has been resolved, you can consider to close this issue.

**Comment by lotuslakestudio** [comment]
Although the origin of the problem has been discovered,  I don't know how to solve it. I tried another program "NPOI". The program generated long text beyond cell limits can not be displayed correctly in ReoGrid, either. Can you fix that?

**Comment by jingwood** [comment]
Can you please provide the xlsx file?

**Comment by lotuslakestudio** [comment]
[temp.xlsx](https://github.com/unvell/ReoGrid/files/11956148/temp.xlsx)
As above.

**Comment by lotuslakestudio** [comment]
Another problem found. When I'm using
`this.reoGridControl1.CurrentWorksheet.Cells["A1"].Data ="very looooooooong text"`
The cell looks good. But if i'm using 
`unvell.ReoGrid.Drawing.RichText rt = new unvell.ReoGrid.Drawing.RichText();
            rt.Regular("very looooooooong text");
            this.reoGridControl1.Worksheets[0].Cells["A1"].Data = rt;`
The same problem happens. The text beyond cell boundary is trimmed.

**Comment by lotuslakestudio** [comment]
I solved this problem finally.
`foreach (var sheet in this.reoGridControl1.Worksheets)
            {
                sheet.EnableSettings(WorksheetSettings.View_AllowCellTextOverflow);
                for (int r = sheet.UsedRange.Row; r <= sheet.UsedRange.EndRow; r++)
                    for (int c = sheet.UsedRange.Col; c <= sheet.UsedRange.EndCol; c++)                    
                        if (sheet.GetCell(r, c) != null && sheet.GetCell(r, c).Data is unvell.ReoGrid.Drawing.RichText)
                            (sheet.GetCell(r, c).Data as unvell.ReoGrid.Drawing.RichText).Overflow = true;
            }`
