### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by waconline** [unvell/ReoGrid#51]
1.how to set Unprintable Cell?
2.how to set Monochrome printing?
3.A problem with editor, "slash" and "backslash" not work
4.EventArgs.cs line 660, public class RowsHeightChangedEventArgs : **WorksheetColumnsEventArgs**

**Comment by jingwood** [comment]
>1.how to set Unprintable Cell?

You can set a print range like Excel does, and cells outside the range will not be printed out. Check property of worksheet `PrintableRange` and this [document](https://reogrid.net/document/paging-and-print).

> 2.how to set Monochrome printing?

You may have to call the print settings API of windows, check the [MSDN](https://msdn.microsoft.com/en-us/library/system.drawing.printing.printersettings(v=vs.110).aspx).

> 3.A problem with editor, "slash" and "backslash" not work

These border format are not support yet.

> 4.EventArgs.cs line 660, public class RowsHeightChangedEventArgs : WorksheetColumnsEventArgs

Thanks!
