### ISSUE TITLE
 About the sheet Name display in the lower left corner

### ISSUE THREAD

**Issue by 1542793315** [unvell/ReoGrid#521]
The sheet name of the file is always hidden
How to adjust the display ratio of this

![image](https://github.com/unvell/ReoGrid/assets/48785885/82ba67af-d341-4efc-a326-e919e1e50250)

It becomes like this
![image](https://github.com/unvell/ReoGrid/assets/48785885/550a08ce-9348-45b5-8633-ff01995f317f)

**Comment by CanadianHusky** [comment]
Use this to set the width to your desired value
`Me.ReoGrid1.SheetTabWidth = 500`

you can probably do more tricks by playing with this object
`Me.ReoGrid1.SheetTabContextMenuStrip`

**Comment by 1542793315** [comment]
@CanadianHusky  thank you ,
About FileFormat.ReoGridFormat 

Does saving in RGB format not support multiple Sheet
I will reload the saved RGF format file and only one Sheet will exist

**Comment by CanadianHusky** [comment]
Did you read the Documentation ?
https://reogrid.net/document/rgf-format/

Multiple worksheet or entire workbook
Current version of ReoGrid does not support saving and loading entire workbook as RGF format. Application should save and load the worksheets by call the method from each worksheet.

Saving and Loading the entire Worksheet as Excel XLSX Format is possible. See https://reogrid.net/document/excel-file-format/

**Comment by 1542793315** [comment]
Oh! Sorry, I didn't read   rgf-format  too carefully!
Thank you！
