### ISSUE TITLE
How to know the coordinates of "Graphics. Point" in "RangePosition" or "CellPosition"

### ISSUE THREAD

**Issue by 1542793315** [unvell/ReoGrid#523]
How to know the coordinates of "Graphics. Point" in "RangePosition" or "CellPosition"
I need to build the Location of ImageObject

**Comment by jingwood** [comment]
The `worksheet` instance has the following methods that might help you.

```cs
public Rectangle GetRangePhysicsBounds(RangePosition range)
public Point GetCellPhysicsPosition(int row, int col)
```

Just notice that the atucal point drawed on screen may not same to the physics position, since worksheet can be frozen, scrolled or zoomed.
