### ISSUE TITLE
about drop-down ListView left

### ISSUE THREAD

**Issue by linxiwell** [unvell/ReoGrid#60]

**Comment by linxiwell** [comment]
How to customize drop-down ListView.left

**Comment by jingwood** [comment]
What do you mean the `ListView.left`? Hope this document helps you:
https://reogrid.net/walkthroughs/how-to-create-custom-drop-down-cell/

**Comment by linxiwell** [comment]
How to make the ListView Aligned to the specified column? that is to say, may the user to specify the ListView Left!

**Comment by jingwood** [comment]
You can't specify a fixed position for your own control, you can only put it into the panel of dropdown cell. The position of dropdown panel will be managed by ReoGrid and changed dynamically when cell resized, spreadsheet scrolled, zoomed or frozen cell specified. 

Check the document above I sent you, try different way to achieve your goal.
