### ISSUE TITLE
Problem on tab color

### ISSUE THREAD

**Issue by Furgia** [unvell/ReoGrid#66]
I have dynamically created a workbook with many worksheets
Using commands

```
grid.Worksheets[1].NameBackColor
grid.Worksheets[1].NameTextColor
```

I can easily assign the color of the various tabs

If after an event I have to update the color, the same commands have no effect.

Do I have to use a command like "commit" to make the variation ?

Thank-you

**Comment by jingwood** [comment]
By some tests I cannot reproduce this problem. Windows Form? or WPF? And Is there any special operations before that happens?

**Comment by Furgia** [comment]
WPF
now I can not see the code (I can do the 8/1) but I remember that to do a test I tried to run the commands after pressing the F1 key (nothing else)

**Comment by jingwood** [comment]
I test this a few times I still can't get it happen. The below code works fine.

```csharp
// event fired from main window
this.KeyDown += (s, e) =>
	{
		if (e.Key == System.Windows.Input.Key.F1)
		{
			grid.Worksheets[0].NameBackColor = Colors.Red;
			grid.Worksheets[0].NameBackColor = Colors.Yellow;
		}
	};
```

If you still face this problem try add the following line after you changed the color.

```chsarp
grid.InvalidateVisual();
```

**Comment by Furgia** [comment]
Does not work.
Probably I'm wrong in defining types.
What is the type of the "grid" object in your example?

My code:
       void worksheet_AfterCellKeyDown (object sender, AfterCellKeyDownEventArgs e)
        {
            string mykey = e.KeyCode.ToString ();
            switch (mykey)
            {
                "F1" houses:
                        (((Worksheet)sender).Workbook).Worksheets[0].NameBackColor = Colors.Green;
                        (((Worksheet)sender).Workbook).Worksheets[0].RequestInvalidate();
                  break;
            default:
                  break;
            }
         }

The color change instruction is successful (I see it debugging) but it has no visual effect.

I used RequestInvalidate on the sheet instead of InvalidateVisual on the workbook because I can not correctly cast the object on which to apply InvalidateVisual but in any case it does not work.

**Comment by jingwood** [comment]
> What is the type of the "grid" object in your example?

@Furgia `grid` is the instance of ReoGrid control.

I recommended that use instance of ReoGrid control by passing as variable rather than use like this `((Worksheet)sender)`, because the casting may fail and you may get the result such this problem.

**Comment by Furgia** [comment]
I solved it with a workaround.
After a certain event changes the color of the tab of some sheets, I need to activate a routine that temporarily makes these sheets as "currentsheet" and then restore the original one.

If sheetchanged is the array that contains the sheet in which the color of the tab has changed

Worksheet[] sheetchanged;
Worksheet current = MyReoGrid.CurrentWorksheet;
foreach (Worksheet s in sheetchanged;
{
	MyReoGrid.CurrentWorksheet = s;
}
MyReoGrid.CurrentWorksheet = MyReoGrid.Worksheets.Where(s => s != current).FirstOrDefault();
MyReoGrid.CurrentWorksheet = current;

**Comment by Furgia** [comment]
I reopen because I did not realize that the solution adopted works perfectly with NameBackColor but not with NameTextColor whose value is always "white".
