### ISSUE TITLE
WPF - Removing a worksheet breaks sheet tabs

### ISSUE THREAD

**Issue by lelimacon** [unvell/ReoGrid#68]
When working with the `ReoGridControl` (v2.1.0) in WPF, the sheet tabs acts unexpectedly after a sheet removal.

![image](https://user-images.githubusercontent.com/7737890/33331982-589720b0-d463-11e7-8ae4-315a0c4d3c20.png)

To reproduce the problem, simply add a few sheets and remove one, like so :
```cs
Grid.NewWorksheet();
Grid.NewWorksheet();
Grid.RemoveWorksheet(0);
```

**Comment by jingwood** [comment]
Thanks! Fixed.
