### ISSUE TITLE
Cell text rotation is not working

### ISSUE THREAD

**Issue by Sesi0** [unvell/ReoGrid#72]
```js
// 'workbook' is the predefined global object for workbook instance of control
//

var sheet = workbook.currentWorksheet;

var cell = sheet.getCell("A1");
cell.Data = 'hello';
cell.Style.RotateAngle = -90;
```

**Comment by jingwood** [comment]
Fixed, please use `rotationAngle` or `RotationAngle` in script from latest version.

![20171217 235856](https://user-images.githubusercontent.com/3468046/34081260-e0ed665c-e38d-11e7-8262-058b3aa51a10.png)

**Comment by Sesi0** [comment]
Is this update avaliable for WPF?

**Comment by jingwood** [comment]
WPF text rotation has been now supported #180
