### ISSUE TITLE
formulas that refer to various sheets

### ISSUE THREAD

**Issue by Furgia** [unvell/ReoGrid#75]
Is it possible to insert a formula that refers to different sheets?
Example "= Sheet1! A1 + Sheet2! A2"
From the tests I have done it would seem that formulas are accepted without the indication of the sheet and that therefore refer only to cells of the same sheet in which they are written.
Example "= A1 + A2"
If it is possible what is the correct syntax for creating the formula ?
Thank you

**Comment by jingwood** [comment]
Did you try this formula?

```
=Sheet1!A1 + Sheet2!A2
```

**Comment by jingwood** [comment]
May get incorrect calculation result caused by #10

**Comment by Furgia** [comment]
I add that the name of my sheets is a number or contains spaces
Can this be the problem?
In fact, if I refer to a sheet called "index", it works,
However, it does not work if the name is "1" "F<SPACE>1" "F1".

**Comment by Furgia** [comment]
second name last paragraph "F" + "space" + "1"

**Comment by Furgia** [comment]
I solved it with a workaround.
I had to change the names of the sheets so that each name
1) does not contain spaces
2) does not contain strings that are also cell identifiers such as  "xxxA1yyy "
The presence of underscore cancels the problem; for example if  the name sheet is "xxxA_1yyy " formula works well.

**Comment by jingwood** [comment]
@Furgia, you can't use `F1` or `xxxA1yyy` as a named range because they are the format of cell address. `xxxA_1yyy` is an valid name for named range.

**Comment by Furgia** [comment]
If in the future you should be able to manage even sheet with names like F1 would be very nice.
Thank you.
