### ISSUE TITLE
can dropdown list cell bind datatable?

### ISSUE THREAD

**Issue by sugemd** [unvell/ReoGrid#81]
can dropdown list cell bind datatable ,just like combobox.
have valuefield and textfield
thanks

**Comment by jingwood** [comment]
You can make your own drop-down cell with a standard .NET ListView or ListBox control inside, use the standard .NET ListView or ListBox to bind the data you want to show. For more details please refer to:  https://reogrid.net/walkthroughs/how-to-create-custom-drop-down-cell/
