### ISSUE TITLE
How to make the ListView window pop-up, align the user to specify the columns, for example, A column or C?

### ISSUE THREAD

**Issue by linxiwell** [unvell/ReoGrid#82]
How to make the ListView window pop-up, align the user to specify the columns, for example, A column or C?

**Comment by jingwood** [comment]
You can make your own drop-down cell with a standard .NET ListView control inside, put it to the cell where you want the drop-down cell shows, and hide the drop-down button. Learn more about drop-down cell: https://reogrid.net/walkthroughs/how-to-create-custom-drop-down-cell/

**Comment by linxiwell** [comment]
listview.MinimumDropdownWidth = Grid1.Width
listview.Left=Grid1.Left???
However no listview. Left properties
