### ISSUE TITLE
How to get and set the CurrentWorksheet of vertical/horizontal scroll bar value?

### ISSUE THREAD

**Issue by linxiwell** [unvell/ReoGrid#83]
How to get and set the CurrentWorksheet of vertical/horizontal scroll bar value?

**Comment by linxiwell** [comment]
example：
x=verticalscroll. value
y=horizontalscroll.value
verticalscroll. value=10
horizontalscroll.value=5

**Comment by jingwood** [comment]
Currently there is no way to get the scroll bar value directly, but you can use an event 'WorksheetScrolled' from workbook instance, to get final value by adding the offset value from argument of event.

**Comment by linxiwell** [comment]
The revolution has not yet been successful, Jing still need efforts
