### ISSUE TITLE
请问ReoGrid可以从数据库读取数据然后绑定显示到ReoGrid控件上嘛？

### ISSUE THREAD

**Issue by ChanthyT** [unvell/ReoGrid#84]
想从数据库读取表内的数据，然后数据绑定显示到ReoGrid中，我在ReoGrid的属性中有看到DataBindings，请问能否实现？

**Comment by linxiwell** [comment]
还可以中文，这样那个日本作者能看懂吗？
你读取出来同时写入控件的单元格不就好了吗？

**Comment by jingwood** [comment]
Please post your issue in English, will close this issue.

**Comment by tan133** [comment]
the two commented 's meaning is tranlate like this:

 ChanthyT commented 4 days ago 
can i use dataBinding when i use datebase

 linxiwell commented 4 days ago 
sir ,you should use english ,and for your problem ,you can read first and then write to the cell
