### ISSUE TITLE
can't compile 

### ISSUE THREAD

**Issue by Jonney3099** [unvell/ReoGrid#89]
I can't compile ReoGrid on my VS2010. Many errors such as:
ReoGrid/Core/AutoFillSerial/TextAutoFillSectionEntry.cs:
1. GetIterationValue:
         `return $"{textLeftOfDigit}{digitText}{textRightOfDigit}";`

Error	1	Unexpected character '$'	E:\C#\ReoGrid\ReoGrid-master\ReoGrid\Core\AutoFillSerial\TextAutoFillSectionEntry.cs	64	20	ReoGrid

2.public class NumericalAutoFillSectionEntry : IAutoFillSectionEntry
           `public object Value { get; }  `

Error	1	'unvell.ReoGrid.NullAutoFillSectionEntry.Value.get' must declare a body because it is not marked abstract or extern. Automatically implemented properties must define both get and set accessors.	E:\C#\ReoGrid\ReoGrid-master\ReoGrid\Core\AutoFillSerial\NullAutoFillSectionEntry.cs	5	31	ReoGrid

        public NumericalAutoFillSectionEntry(double value)
        {
            Value = value;  //Read only, can't assign!
        }
Error	23	Property or indexer 'unvell.ReoGrid.NumericalAutoFillSectionEntry.Value' cannot be assigned to -- it is read only	E:\C#\ReoGrid\ReoGrid-master\ReoGrid\Core\AutoFillSerial\NumericalAutoFillSectionEntry.cs	9	13	ReoGrid

**Comment by jingwood** [comment]
Please try with Visual Studio 2015 or higher.
