### ISSUE TITLE
Saving worksheet that contains image cells

### ISSUE THREAD

**Issue by jingwood** [unvell/ReoGrid#9]
- Save images in .RGF format

Original post at https://reogrid.net/forum/viewtopic.php?id=504

**Comment by 1299699825** [comment]
Has the above problem been solved?

**Comment by 1299699825** [comment]
hello,
Excuse me, can I save images in .rgf file now ?

**Comment by jingwood** [comment]
I think it is not supported yet.

**Comment by jingwood** [comment]
Implemented by #200
