### ISSUE TITLE
Adjust of column width to size of main window

### ISSUE THREAD

**Issue by JoSell95** [unvell/ReoGrid#90]
Is there a way to adjust the column width to the size of the main window, so that the last column fills the whole reogrid control:

![grafik](https://user-images.githubusercontent.com/33544851/35558535-96992c20-05a8-11e8-9eb3-7eab2b215705.png)

The column "Description" should automatically fill the reogrid control

**Comment by jingwood** [comment]
You can set it manually. 

Catch the event when ReoGrid resized, set the width of last column by using `Column[2].Width = ` property.
