### ISSUE TITLE
Why not find "Load" event for ReoGridControl

### ISSUE THREAD

**Issue by waconline** [unvell/ReoGrid#92]
Why not find "Load" event for ReoGridControl, if not exist, how to add "Load" event?

**Comment by jingwood** [comment]
Because ReoGrid loads worksheet synchronously, the event is the end of calling `load` method. What's the case you need a load event?

**Comment by waconline** [comment]
Because some initialization methods place into load event method is the best. Similar to WinForm.OnLoad() method.
Ex. 1)My ReoGrid has 3 worksheets ws0,ws1,ws2. 
      2)ws0 has 1 thing ws0.CellDataChanged += grid1_CellChange;
      3)ws1 has 1 thing ws1.CellMouseUp += grid2_MouseClick;
      4)ws2 has 1 thing ws2[1, 1] = new ListViewDropdownCell();
